README.md
cb/cb.py
cb/cb_magma.py

Rename Cb to CB and add naming conventions to README.

---

conftest.py
test_mem/build/.gitignore
test_mem/sram_stub.v
test_mem/test_mem_genesis2.py

Implements the SRAMPhases test from the old CGRAGenerator memory tests using fault and magma.

Directed test mem

---

.travis.yml
README.md

Forgot to update the travis script.

Rename mem in travis script

---

common/util.py
test_common/test_util.py

A simple way to mark functions as deprecated w/ a message. For now all
deprecated functions raise an exception. In the future we want to
introduce a warning mode.

Add deprecation decorator

---

test_sb/sb_tb.v
test_sb/test_sb_regression_verilog_sim.py

Wrote a directed test for SB in Verilog that tests multiple scenarios for a given set of parameters. Added the python wrapper to run generate the Genesis output files and run the TB.

Directed test for SB

---

common/irun/cmd.tcl
test_global_controller/genesis/test.svp

This adds the improved global controller testbench that I've been working on in CGRAGenerator. I created tasks for the global controller ops and added system verilog assertions to verify the GC is behaving correctly.

Improved gc tb

---

common/config_register.py
test_common/gold/config_register.json
test_common/test_config_register.py

The mux logic in mantle was changed so we need to update the gold file.

Update gold file for upstream mantle change

---

test_common/gold/config_register.json

Wrappers removed for eq and and and circuits

Update gold for config register

---

test_simple_pe/test_simple_pe_magma.py

See https://github.com/phanrahan/magma/pull/272/files for changes to how parameters are passed on to the coreir backend

Update compile invocation based on upstream magma change

---

.travis.yml
setup.py
test_simple_pe/test_simple_pe_magma.py

See https://github.com/cristian-mattarei/CoSA/issues/35#issuecomment-423042984 for details on the `problem.txt` change

Update to cosa 0.2.1

---

requirements.txt
setup.py

Welcome to a new era of PYPI versioned magma/mantle packages!

Use PYPI release of magma and mantle

---

test_cb/test_cb_regression_verilog_sim.py
test_common/hello_world.sv
test_global_controller/test_global_controller_verilog_sim.py
test_sb/test_sb_regression_verilog_sim.py

This PR simply resolves ncsim errors in #125 
It also resolves a ncsim error on `test_run_verilog_sim.py`

Fix ncsim errors

---

.travis.yml
README.md
cb/cb_genesis2.py
cb/cb_magma.py
cb/cb_magma_orig.py
column/column_magma.py
common/genesis_wrapper.py
global_controller/global_controller_genesis2.py
interconnect/circuit.py
interconnect/cyclone.py
interconnect/interconnect.py
interconnect/sb.py
interconnect/tile_circuit.py
interconnect/util.py
memory_core/memory_core_genesis2.py
pad_frame/pad_frame_genesis2.py
pe_core/pe_core_genesis2.py
sb/sb.py
sb/sb_genesis2.py
setup.cfg
simple_cb/simple_cb_genesis2.py
simple_cb/simple_cb_magma.py
simple_pe/simple_pe.py
test_cb/test_cb_regression.py
test_common/test_genesis_wrapper.py
test_global_controller/test_global_controller.py
test_interconnect/test_cyclone.py
test_pe_core/test_pe_core.py
test_simple_sb/test_simple_sb_magma_no_model.py
top/top_magma.py

Closes https://github.com/StanfordAHA/garnet/issues/142

Pycodestyle

---

docs/test_plan.md

This is a document we'll use to organize the overall test plan for the chip. This should be a collaborative document that others should feel empowered to update with their own testing plans.
This will eventually also include a style guide and other related documentation for testing practices.

Init test plan

---

cb/cb_magma_orig.py
interconnect/cyclone.py

For some reason some of the code were not checked by `pycodestyle` yet resurfaced in a branch. This PR fixes these style issue.
See: https://travis-ci.org/StanfordAHA/garnet/builds/486034045
EDIT: it seems like there is a new release from pycodestyle: https://pypi.org/project/pycodestyle/#history
EDIT EDIT: Yep the release notes confirmed my guess: https://github.com/PyCQA/pycodestyle/commit/e91ef6e40f2be30f9af7a86a84255d6bdfe23f51

fix pycodestyle

---

requirements.txt
tests/test_interconnect/test_interconnect_cgra.py
top/top_magma.py

See PR https://github.com/rsetaluri/canal/pull/4

Add step to freeze features

---

requirements.txt

Required changes from our fork were merged into master and released

Move to pypi pyverilog

---

tapeout_16/scripts/layout_Tile_PECore.tcl
tapeout_16/scripts/synthesize.tcl
tapeout_16/scripts/upf.port.fix.tcl

Incremental fixes to synthesis & P&R scripts.

Tapeout-pd

---

garnet.py
requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

Based on https://github.com/StanfordAHA/canal/tree/new_global_wiring

use new io semantics in global wiring

---

tapeout_16/scripts/layout_Tile_MemCore.tcl

Tapeout_pd

---

io_core/io16bit_magma.py
io_core/io1bit_magma.py
memory_core/memory_core_magma.py
peak_core/peak_core.py
requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

Add information in each core so that information can be automatically passed through the flow.

Update core interface

---

cgra/__init__.py
cgra/util.py
garnet.py
tests/test_garnet/test_garnet.py
tests/test_interconnect/test_interconnect_cgra.py

1. Merged the CGRA creation
2. Add a test to `garnet.py`. Because it's not a module, I have to use subprocess to run it.

Unify the cgra creation and add garnet test

---

tapeout_16/scripts/layout_Tile_MemCore.tcl
tapeout_16/scripts/layout_Tile_PECore.tcl
tapeout_16/scripts/upf.port.fix.tcl

Tapeout PD

---

global_buffer/genesis/global_buffer.svp
global_buffer/genesis/global_buffer_int.svp

Just a hotfix to change global buffer parameter

Fix global buffer parameter

---

cgra/util.py
power_domain/pd_pass.py
requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

This is an improved implementation of power domain pass based on the discussion here: https://github.com/StanfordAHA/gemstone/pull/17#issuecomment-488527636
It relies on the `or_reduction` pass change here: https://github.com/StanfordAHA/gemstone/pull/21

finish up advanced power domain pass

---

memory_core/memory_core_magma.py

This gives us about a minute when generating big chips.

cache memory core creation

---

memory_core/memory_core_magma.py

Deal with the problem where `flush` sometimes will be routed to to other 1-bit signals, e.g. global soft reset.

add const registers to the control signals

---

memory_core/genesis_new/fifo_control.svp
memory_core/genesis_new/linebuffer_control.svp

Did this from my iPhone please fix spacing

Hotfix to linebuffer to add flush

---

tapeout_16/scripts/synthesize.tcl

Constraint update to match mux RTL update.

Power aware synthesis constraint update

---

tapeout_16/scripts/layout_Tile.tcl

Pwr aware P&R updates

---

cgra/util.py
garnet.py
memory_core/genesis_new/mem.vp
memory_core/genesis_new/memory_core.svp
memory_core/memory_core_genesis2.py
memory_core/memory_core_magma.py
tests/test_memory_core/test_memory_core.py

This prevents me from having to manually change the sram instantiation when I want to synthesize the design.

add flag to use real sram instead of stub

---

power_domain/pd_pass.py

Update logic in PowerDomainOR

---

tapeout_16/gls/cmd.tcl
tapeout_16/gls/liblist
tapeout_16/gls/tb_Tile_PE.v
tapeout_16/run_all.csh
tapeout_16/scripts/run_ncsim_Tile_PE.csh

Setup to run power aware GLS after P&R completes.

Pwr Aware Gate level simulations (GLS)

---

tapeout_16/scripts/layout_Tile.tcl
tapeout_16/scripts/params.tcl

Update AON region gen & UPF ptr.

AON region gen & UPF ptr update

---

.gitignore
memory_core/genesis_new/linebuffer_control.svp
memory_core/genesis_new/mem.vp
tests/test_interconnect/test_interconnect_cgra.py

Fixed the logic and added unit test for the valid out of the last row of a row buffer

Stencil valid

---

global_controller/genesis/global_controller.svp
tests/test_global_controller/genesis/test.svp

Change CGRA default clock to system clock from JTAG clock
(request by @thenextged)
@THofstee should also know about this change.

Change CGRA default clock to sys_clk

---

global_controller/genesis/global_controller.svp

Simple fix to change default stall register value

Change default clock_Stall

---

memory_core/genesis_new/doublebuffer_control.svp
memory_core/genesis_new/fifo_control.svp
memory_core/genesis_new/linebuffer_control.svp
memory_core/genesis_new/memory_core.svp

Removed all mods so Alex can actually synthesize

should get rid of all mods

---

tapeout_16/scripts/upf_Tile_MemCore.tcl
tapeout_16/scripts/upf_Tile_PE.tcl

keep tile_id AON

---

tapeout_16/gls/tb_Tile_MemCore.v
tapeout_16/scripts/run_ncsim_Tile_MemCore.csh

Gate level simulation tests passing post new changes for MEM & PE tiles.

GLS updates

---

global_controller/genesis/global_controller.svp

Remove latch in global controller

---

tapeout_16/scripts/layout_Tile.tcl

Tap cell, PG VDD_SW updates

---

global_buffer/genesis/io_controller.svp
global_buffer/global_buffer_bs_generator.py
global_buffer/global_buffer_mapper.py
tests/test_collateral_pass/test_glb_config_reg.py

In this PR, all the configuration registers for `global_buffer` are dumped as `.json` file.
Also, it generates corresponding bitstream for `global_buffer` as you change `address generator` in the `global buffer`

Collateral pass to generate global buffer configuration and bitstream

---

.gitignore
memory_core/genesis_new/doublebuffer_control.svp
memory_core/genesis_new/fifo_control.svp
memory_core/genesis_new/linebuffer_control.svp
memory_core/genesis_new/memory_core.svp
memory_core/memory_core_magma.py
tests/test_interconnect/test_interconnect_cgra.py
tests/test_interconnect/test_reset.py

adds handcrafted fifo test that does lots of good checking of valid, data, empty, full

fifo_test_comprehensive

---

tests/test_interconnect/test_stall.py

Tests stalling on pipeline register, PE operand registers, and LB.

add stall test

---

cgra/util.py
tests/test_interconnect/test_interconnect_cgra.py

Should address the issue in https://github.com/StanfordAHA/garnet/issues/308

fix io fanout guard

---

memory_core/genesis_new/doublebuffer_control.svp

made some earlier changes that needed to be updated here

fix wen RTL BUG

---

memory_core/genesis_new/doublebuffer_control.svp
tests/test_interconnect/test_interconnect_cgra.py

fix changes for arbitrary mode of double buffer w/ test added 

---

memory_core/genesis_new/doublebuffer_control.svp
memory_core/genesis_new/fifo_control.svp
memory_core/genesis_new/linebuffer_control.svp
memory_core/genesis_new/memory_core.svp
memory_core/genesis_new/sram_control.svp
tests/test_interconnect/test_stall.py

In a battle of latches vs rtl-level write-enables, who will be the victor?

A NEW CHALLENGER APPROACHES: Clock gate mem tile fix

---

global_controller/genesis/global_controller.svp
tests/test_global_controller/genesis/test.svp

Update auto restart

---

mini_mapper/__init__.py

Gate chain_wen_in of the first memory tile in a chain so that valid_out is not high all the time.

Add gating for chain_wen_in

---

requirements.txt

Revert to peak master

---

peak_core/peak_core.py
requirements.txt

assembler fixes for the branch that is being used in GarnetFlow

Simple mapper assembler

---

global_buffer/io_placement.py

Add ability to have multiple valid signals

Fix mapper to handle multiple valid signals

---

peak_core/peak_core.py
requirements.txt

This is needed for https://github.com/cdonovick/peak/pull/109 to pass.

Adhere to peak:interface changes

---

mflowgen/README.md

I wrote a README for the mflowgen directory. Let me know and/or edit directly if I got it wrong.

README for mflowgen directory

---

global_buffer/rtl/TS1N16FFCLLSBLVTC2048X64M8SW.sv
global_buffer/rtl/glb_bank.sv
global_buffer/rtl/glb_bank_controller.sv
global_buffer/rtl/glb_cfg_address_generator.sv
global_buffer/rtl/glb_cfg_interconnect.sv
global_buffer/rtl/glb_fbrc_address_generator.sv
global_buffer/rtl/glb_fbrc_interconnect.sv
global_buffer/rtl/glb_host_interconnect.sv
global_buffer/rtl/glb_memory_core.sv
global_buffer/rtl/glb_memory_module.sv
global_buffer/rtl/glb_sram_controller.sv
global_buffer/rtl/glb_sram_gen.sv
global_buffer/rtl/glb_tile.sv
global_buffer/rtl/global_buffer.filelist
global_buffer/rtl/global_buffer.sv
global_buffer/rtl/global_buffer_pkg.sv
global_buffer/rtl/interface/cfg_ifc.sv

@kong0329 please make sure that this is the up-to-date RTL. It's directly from current tapeout branch.

copied glb rtl from tapeout branch

---

mflowgen/glb_tile/construct.py
mflowgen/glb_tile/custom-init/outputs/floorplan.tcl
mflowgen/glb_tile/custom-init/outputs/pin-assignments.tcl
mflowgen/glb_tile/custom-power/outputs/power-strategy-dualmesh.tcl
mflowgen/glb_top/constraints/constraints.tcl
mflowgen/glb_top/construct.py
mflowgen/glb_top/custom-init/configure.yml
mflowgen/glb_top/custom-init/outputs/dont_touch.tcl
mflowgen/glb_top/custom-init/outputs/floorplan.tcl
mflowgen/glb_top/custom-init/outputs/pin-assignments.tcl
mflowgen/glb_top/custom-power/outputs/power-strategy-dualmesh.tcl
mflowgen/glb_top/glb_tile/configure.yml
mflowgen/glb_top/glb_tile/get_glb_outputs.sh

-adjusted tile and top sizes to reduce area
-added dont_touch to nets between abutted tiles to prevent insertion of unroutable buffers between them
-added power stripes for SRAMs
-added halos to macros to fix DRCs

various changes to GLB flow to fix routing issues and DRCs

---

cgra/util.py
mini_mapper/__init__.py
peak_core/peak_core.py
requirements.txt
tests/test_interconnect/test_stall.py
tests/test_peak_core/test_pe_config.py
tests/test_peak_core/test_pe_stall.py

Changes required for https://github.com/StanfordAHA/lassen/pull/164

Lassen cleanup

---

cgra/util.py
mini_mapper/__init__.py
requirements.txt
tests/test_interconnect/test_stall.py
tests/test_peak_core/test_pe_config.py
tests/test_peak_core/test_pe_stall.py

Reverts StanfordAHA/garnet#420

Revert "Lassen cleanup"

---

bin/requirements_check.sh
bin/verify_eggs.sh
mflowgen/test/post-rtl-filter.awk
mflowgen/test/rtl-filter.awk
mflowgen/test/test_pe.sh

Working buildkite script for Tile_PE DRC, with pass/fail criteria. See https://buildkite.com/tapeout-aha/mflowgen/builds for examples of recent builds.

Buildkite dev

---

power_domain/pd_pass.py

See https://github.com/StanfordAHA/canal/pull/23

Flatten PD mux's for canal changes

---

requirements.txt

pointing lassen to master

---

global_buffer/global_buffer_magma_helper.py
mflowgen/glb_tile/rtl/gen_rtl.sh

Quick fix to run `make` within mflowgen flow to generate all rtl files.

This is a fix to run make in mflowgen flow

---

garnet.py

This updates compilation of magma circuits to infer clock gating structures.

added clock gating passes to garnet

---

mflowgen/glb_top/rtl/gen_rtl.sh

Quick fix to add parameter file in `glb_top` mflowgen flow.

Add param file to rtl flow

---

global_controller/Makefile
mflowgen/global_controller/construct.py
mflowgen/global_controller/rtl/configure.yml
mflowgen/global_controller/rtl/gen_rtl.sh

This PR add custom rtl step to global controller.
Tested mflowgen generating `design.v` file correctly.

Add custom rtl step to global controller

---

peak_core/data_gate.py
peak_core/peak_core.py
tests/test_peak_core/test_pe_config.py

-- Added 16 bit float op to data-gated ops
-- Added 16 bit mult op to data-gated ops (required some hard-coded stuff)
Added tests for both. Also required some refactoring of the code.

Finish data gate pe

---

.buildkite/pipeline_mflowgen.yml
mflowgen/test/expected_result/glb_tile

Adds an mflowgen buildkite test for the glb_tile

Add glb_tile buildkite flow

---

.buildkite/pipeline_mflowgen.yml
mflowgen/common/init-fullchip/outputs/check-bumps.tcl
mflowgen/common/init-fullchip/outputs/route-bumps.tcl

More power/ground bumps. More direct routes.
Implements the changes discussed in detail in issue https://github.com/StanfordAHA/garnet/issues/493

Betterbumps

---

.travis/run.sh
requirements.txt

Also removed LD_LIBRARY_PATH hack in travis run script.

Use pycoreir wheel instead of master

---

mflowgen/full_chip/construct.py
mflowgen/pad_frame/construct.py

If you want to DRC after the metal fill step, you'll have to change the rule deck and design name parameters for DRC. The design name should be ${original_design_name}_filled. You should use the full chip DRC deck to surface any metal density issues. This rule deck also expects a sealring.

param updates for full_chip and pad_frame + metal fill in pad_frame

---

global_buffer/rtl/glb_tile_pc_switch.sv
global_buffer/testbench/glb_test.sv
global_controller/design/genesis/glc_jtag_ctrl.svp

This PR adds control logic to bypass configuration packet If configuration read is enabled.

Add control logic to bypass configuration if read is enabled

---

mflowgen/full_chip/custom-lvs-rules/outputs/rules.svrf

LVS passes on soc_only full_chip with this change.

lvs box sram in full_chip flow

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py

Looks like those other changes in #516 weren't merged properly... Must be a github bug.

remove condition on PWR_AWARE variable update

---

global_controller/design/genesis/glc_axi_ctrl.svp

Change `wready` reset value from `1` to `0`.

Change reset value of wready in axi

---

global_buffer/systemRDL/ordt_params/glb.parms
global_controller/systemRDL/ordt_params/glc.parms

Set `use_async_reset` to true in `systemrdl` ordt param

Change to async reset

---

mflowgen/full_chip/construct.py

Fixes bug where sealring is added after gds stream out in fullchip flow, and moves fullchip flow to chip-level DRC rule deck.

Fullchip drc

---

global_buffer/rtl/glb_tile_cfg_ctrl.sv
global_buffer/rtl/global_buffer.sv
global_buffer/testbench/glb_test.sv
global_buffer/testbench/reg_driver.sv
global_controller/design/genesis/glc_axi_ctrl.svp
global_controller/testbench/genesis/glc_prog.svp

`glb_tile` Configuration pipeline bug fix.
@hofstee After this branch passes your test, can you approve?

Configuration pipeline bug fix.

---

.buildkite/pipeline_mflowgen.yml
mflowgen/test/test_module.sh

Per-buildkite-step virtual environments, as requested.

Per step venv

---

mflowgen/Tile_PE/constraints/common.tcl
mflowgen/Tile_PE/constraints/configure.yml
mflowgen/Tile_PE/constraints/constraints.tcl
mflowgen/Tile_PE/constraints/outputs/common.tcl
mflowgen/Tile_PE/constraints/outputs/reporting.tcl
mflowgen/Tile_PE/constraints/reporting.tcl
mflowgen/Tile_PE/construct.py
mflowgen/common/power-domains/configure.yml
mflowgen/common/power-domains/outputs/designer-interface.tcl
mflowgen/common/power-domains/outputs/pe-constraints-2.tcl
mflowgen/common/power-domains/outputs/pe-constraints.tcl

Updated PE timing constraints.
A lot of it is the same as that in the mem tile.

Updated PE timing constraints

---

mflowgen/test/test_module.sh

Per Alex request, ignore DRC errors.

ignore drc errors

---

mflowgen/test/test_module.sh

Per Alex request, ignore DRC errors, second attempt. Also see previous (failed) fix https://github.com/StanfordAHA/garnet/pull/546

Ignore DRC errors - prev attempt failed too soon

---

mflowgen/global_controller/constraints/constraints.tcl
mflowgen/global_controller/construct.py

This PR is update in global controller constraint file.
Changes are
(1) change clock period
(2) setting clk_in -> clk_out false path

Global controller constraint for PD timing

---

.buildkite/setup.sh
mflowgen/common/init-fullchip/outputs/route-bumps.tcl

Removes routing for bumps that will be supplied later by Sung-Jin; corrects unrouted PHY jtag signal.

Remove phybumps

---

mflowgen/full_chip/constraints/cons_scripts/constraints.tcl
mflowgen/full_chip/constraints/cons_scripts/garnet_constraints.tcl

Multicycle path for read_config_data at top level. @thenextged I'm not sure how you wanted to organize these kinds of constraints...

Multicycle paths for config_rd_data paths

---

mflowgen/glb_top/constraints/constraints.tcl
mflowgen/global_controller/constraints/constraints.tcl
mflowgen/global_controller/construct.py

This PR set max transition for global buffer and global controller.
I also added `postroute_hold` step to global controller.

Set max transitionfor global buffer and global controller

---

mflowgen/common/init-fullchip/outputs/route-bumps.tcl

Reverts StanfordAHA/garnet#569
Let's wait to merge this before we confirm everything, but I think it's the right thing to do. Sorry again, Steve.

Revert "exclude power/ground routing in PHY JTAG region..."

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/common/power-domains/configure.yml
mflowgen/common/power-domains/outputs/check-clamp-logic-structure.tcl
mflowgen/common/power-domains/outputs/dont-touch-constraints.tcl

PR has following updates:
- Constraint buffering to the clamp logic
- Relax dont_touch constraint on clamp logic to size_only
- Extend postconditions to check if the clamping logic is maintained as expected

No buffering to clamp logic constraints and clamp logic related checks

---

mflowgen/full_chip/constraints/cons_scripts/clocks_3_tlx.tcl
mflowgen/full_chip/constraints/cons_scripts/io.tcl
mflowgen/full_chip/constraints/cons_scripts/pad_strength.tcl

Please review my ```set_case_analysis``` in pad_strength.tcl constraints file

relaxed TLX clock and set_case_analysis for pad strength

---

mflowgen/full_chip/constraints/cons_scripts/io.tcl

Don't mind this. It's a small change that doesn't concern you much

tpiu delays back to 0.5

---

mflowgen/common/init-fullchip/outputs/route-bumps.tcl
mflowgen/pad_frame/construct.py

Fix rdl short

---

mflowgen/full_chip/constraints/cons_scripts/io.tcl

I made an RTL change to fix the recovery issue on reset with the fast clocks

updated constraints on Trace output

---

mflowgen/full_chip/constraints/cons_scripts/clocks_except_soc.tcl

additional false paths on the TLX traning module

added false_path exceptions on TLX training lane enable signals

---

mflowgen/full_chip/constraints/cons_scripts/clocks_3_tlx.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_7_trace.tcl
mflowgen/full_chip/constraints/cons_scripts/io.tcl

Changed `data change window` size for TLX fwd signals

updated TLX constraints

---

mflowgen/full_chip/constraints/cons_scripts/clocks_except_soc.tcl

Updated clock switch design and constraints

updated clock switch

---

mflowgen/common/power-domains/outputs/check-clamp-logic-structure.tcl

Updates to clamp logic assertion and allow antenna cells on the path from the SB input ports for the clamp structure check.

Clamp Logic Assertions & Antenna Cell Checks

---

README.md
bin/requirements_check.sh
bin/verify_eggs.sh
garnet.py
mflowgen/test/test_module.sh

Built (upgraded) a tool that checks your environment and tries to see if it's sufficient to build a garnet chip.
Usage: $GARNET_HOME/bin/requirements_check.sh
Sample output:
```
% bin/requirements_check.sh
------------------------------------------------------------------------
ENVIRONMENT VARIABLES
***ERROR GARNET_HOME env var not set, you're sure to come a cropper
Should probably do: export GARNET_HOME=/nobackup/steveri/github/garnet
***ERROR OA_HOME=/cad/cadence/ICADV12.30.712.lnx86/share/oa,
should be unset, should do: unset OA_HOME
------------------------------------------------------------------------
CAD TOOLS
***ERROR Genesis2.pl not found; recommend you do something like
source $GARNET_HOME/.buildkite/setup.sh
***ERROR calibre not found; recommend you do something like
source …
```

Fix environment

---

mflowgen/setup-garnet.sh

Unified module load script for all Garnet blocks

Add module load script for all of garnet

---

mflowgen/glb_tile/constraints/constraints.tcl

I think we should be able to put the corner stuff in some generic script.

changes to glb_tile constraints for genus compat

---

mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_MemCore/constraints/constraints.tcl

Removed the case_analysis stuff and made some changes so that it works with Genus.

simplified Tile_MemCore constraints + genus compat

---

conftest.py
requirements.txt

Depends on https://github.com/phanrahan/magma/pull/796 and https://github.com/leonardt/pycoreir/pull/143

Use magma frontend API for context reset

---

mflowgen/test/test_module.sh

Fixes master so that buildkite works with the new genus step

update test_module for genus maybe

---

.travis/run.sh
requirements.txt
tests/test_memory_core/test_memory_core.py

- updates LAKE_STREAM and LAKE_CONTROLLER paths in conv_3_3 test
- updates travis for new LAKE_STREAM path
- (temporary) changes lake branch to heur lake until merged into lake master
Lake PR: https://github.com/StanfordAHA/lake/pull/62
AHA branch to check things are working: lake_conv33

Lake: updating to heuristic conv 33 test in garnet

---

mflowgen/bin/setup-buildkite.sh
requirements.txt

lake requirements

---

mflowgen/full_chip/glb_top/configure.yml
mflowgen/full_chip/glb_top/get_glb_top_outputs.sh
mflowgen/glb_tile/construct.py
mflowgen/glb_top/construct.py
mflowgen/glb_top/glb_tile/configure.yml
mflowgen/glb_top/glb_tile/get_glb_outputs.sh

Switches all glb flows to use genus-genlib

Convert glb to genus-genlib

---

global_buffer/global_buffer_magma.py
mflowgen/common/rtl/gen_rtl.sh
mflowgen/full_chip/construct.py
mflowgen/full_chip/glb_top/configure.yml
mflowgen/full_chip/global_controller/configure.yml
mflowgen/glb_tile/rtl/gen_rtl.sh
mflowgen/glb_top/construct.py
mflowgen/glb_top/glb_tile/configure.yml
mflowgen/glb_top/rtl/gen_rtl.sh
mflowgen/global_controller/rtl/gen_rtl.sh

RTL step concatenate global buffer sv

RTL step concatenate global buffer sv

---

.buildkite/pipeline_fullchip.yml
.buildkite/pipeline_mflowgen.yml

Small updates to buildkite pipelines to make them consistent with recent Cadence migration related changes.

Buildkite updates

---

mflowgen/full_chip/construct.py

Relies on https://github.com/mflowgen/mflowgen/pull/85

Add pegasus-fill node to full_chip

---

mflowgen/full_chip/construct.py

Add merge_fill params

---

cgra/util.py
mflowgen/Tile_PE/constraints/constraints.tcl
tests/test_memory_core/test_pond.py

This PR includes the following updates:
- Connect ALU output to Pond input CB
- Add accumulation test for Pond
- Update generate_pond_api function to support strides for rd/wr schedule that's different from the actual rd/wr strides
- Update other Pond tests to match the changes in the above function
No significant timing and area delta between the master PE and this branch. LVS is clean.

Pond Updates

---

tbg.py

Fix the bug on tbg read back where config pipeline regs are inserted

---

mflowgen/tile_array/construct.py

Small update to increase hold fixing margin in tile array

Increase tile array hold slack margin

---

tests/test_memory_core/test_pond.py

We forgot to update this before merging to master...

add the enables to the pond api

---

mflowgen/full_chip/construct.py

Reverts cgra size change from #763 back to 32x16.

Revert cgra size to 32x16

---

mflowgen/glb_top/glb_tile/get_glb_outputs.sh

It adds a fix to solve assertion error!

Copy sram .lib files

---

cgra/util.py
cgra/wiring.py
garnet.py
global_controller/global_controller_genesis2.py
global_controller/global_controller_magma.py
global_controller/rtl/genesis/glc_axi_addrmap.svp
global_controller/rtl/genesis/global_controller.svp
global_controller/systemRDL/rdl_models/glc.rdl
memory_core/memory_core_magma.py
memory_core/memtile_util.py
memory_core/pond_core.py
passes/collateral_pass/config_register.py
passes/interconnect_port_pass/interconnect_port_pass.py
peak_core/peak_core.py

This PR includes CGRA changes for double buffering.
1. Add double buffering control register. (this is an argument to make it backward compatible)
2. Print out the number of configuration register bit size.

Add double buffer to configuration space in CGRA.

---

conftest.py
peak_core/data_gate.py
requirements.txt
tests/test_peak_core/test_pe_config.py

NOTE: WIP. Not an actual PR.
EDIT: Now a real PR, ready for merging.

Fix magma uniq. issues

---

mini_mapper/__init__.py

I modify the mini mapper a little bit for mapping the clockwork auto-gen application pass aha test.

Fix Mini mapper 

---

memory_core/memory_core_magma.py
memory_core/memory_mode.py
mini_mapper/__init__.py

Clean up the configuration interface in memory tile for simpler extension + more readable code.
Current buildkite in aha regression - https://buildkite.com/stanford-aha/aha-flow/builds/4977

Memory tile config clean

---

memory_core/memory_core_magma.py

This check is for posterity - communication through assertion?

add assert for checking rom size length in mapping code

---

mini_mapper/__init__.py

Add mult_middle and a register pack fix to enable rom pass.

Merge register pack change into master

---

memory_core/pond_core.py
mini_mapper/__init__.py
tbg.py
tests/test_memory_core/test_pond.py

Updates to pond_core & mini mapper to get the Pond mapping (aha map) to work.

Updates for pond mapping

---

global_buffer/rtl/glb_tile.filelist

Fix glb-tile filelist

---

mflowgen/glb_top/sim-compile/configure.yml
mflowgen/glb_top/sim-compile/run_sim.sh
mflowgen/glb_top/sim-gl-compile/configure.yml
mflowgen/glb_top/sim-gl-compile/run_sim.sh
mflowgen/glb_top/sim-run/configure.yml
mflowgen/glb_top/sim-run/run_sim.sh

I forgot to commit these nodes in the last PR.
These are mflowgen nodes that runs RTL simulation and gate-level simulation on `global buffer`

Add missing global buffer mflowgen sim node

---

mflowgen/glb_top/sim-gl-run/configure.yml
mflowgen/glb_top/sim-gl-run/run_sim.sh

Add missing files for `sim-gl-run` node.

Add missing files for sim-gl-run node

---

mflowgen/common/rtl/gen_rtl.sh

Copy glc header only when glc is used

---

global_buffer/design/glb_tile_pcfg_switch.py
global_controller/systemRDL/rdl_models/glc.rdl

Change kratos for loop to python for loop

---

tests/test_interconnect/test_interconnect_cgra.py
tests/test_interconnect/test_reset.py
tests/test_interconnect/test_stall.py
tests/test_memory_core/test_memory_core.py
tests/test_memory_core/test_pond.py

Fixed the failing tests from https://github.com/StanfordAHA/garnet/pull/834#issuecomment-1049073896

Updated tests to expect 3 values back from pnr call

---

tests/test_app/Makefile
tests/test_app/lib/map.c
tests/test_app/tb/environment.sv
tests/test_app/tb/kernel.sv

Fix groupsize and return error when pixels mismatch

---

garnet.py
global_buffer/design/glb_cfg.py
global_buffer/design/glb_header.py
global_buffer/design/glb_pcfg_dma.py
global_buffer/design/glb_tile.py
global_buffer/design/global_buffer_parameter.py
global_buffer/gen_global_buffer_rdl.py
tests/test_app/tb/environment.sv
tests/test_app/tb/garnet_test.sv

Add dpr relocation register

---

memory_core/memory_core_magma.py

https://github.com/StanfordAHA/lake/pull/123

update tsmc tech map instance for lake changes

---

mflowgen/tile_array/custom-init/outputs/pin-assignments.tcl

close-square-bracket

---

cgra/util.py
garnet.py
passes/clk_pass/clk_pass.py

add parameterized layout exploration for # tracks, mem ratio, and col/row layout in garnet

Add array option

---

mapper/netlist_util.py

Needed to get garnet master merged into aha master flow

Fix input broadcasts

---

passes/power_domain/pd_pass.py

This should improve synthesis quality when power domain is not used. Linked with https://github.com/StanfordAHA/canal/pull/45
See CI test: https://buildkite.com/stanford-aha/aha-flow/builds/6637

remove aoi mux replacement since canal uses aoi mux by default

---

garnet.py

Needs gemstone: https://github.com/StanfordAHA/gemstone/pull/54 and Canal: https://github.com/StanfordAHA/canal/pull/46
This should allow ready-valid interconnect.
See CI: https://buildkite.com/stanford-aha/aha-flow/builds/6678#41fcecb4-3def-4b7f-9af6-b4479a9f7eec

use ndarray to make it consistent with upstream tools

---

cgra/wiring.py

Remove duplicated wiring

---

.buildkite/pipeline_fullchip.yml
.buildkite/pipeline_mflowgen.yml
.buildkite/pipelines/pe_4x2_rtl.yml
.buildkite/pipelines/pe_gls_standalone.yml
.buildkite/pipelines/pe_synth_only.yml
.buildkite/pipelines/pe_tile_only.yml
mflowgen/bin/buildcheck.sh

Updates to various buildkite pipelines that are available for occasional debugging of the chip build.
For the most part, these changes affect nothing and no one but me, so after the checks, plus some appropriate period for reflection, I will probably go ahead and merge them.

Uniquified pe

---

.buildkite/pipeline_mflowgen.yml
mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_PE/constraints/common.tcl
mflowgen/common/custom-genlibdb-constraints/genlibdb-constraints.tcl
mflowgen/common/synopsys-ptpx-gl/loop_break_Interconnect.tcl

See pull https://github.com/StanfordAHA/garnet/pull/901 which failed because the new rmux-finding pattern was too imprecise. This new pattern is proven to work.

Missing rmux fix

---

global_buffer/design/glb_clk_en_gen.py

Force magma to uniquify

---

mflowgen/full_chip/constraints/cons_scripts/clocks_0_params.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_1_master.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_2_sys.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_3_tlx.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_except_soc.tcl
mflowgen/full_chip/constraints/cons_scripts/io.tcl

constraints update

---

mflowgen/test/test_module.sh

`test_module.sh` was originally conceived as a standalone way of testing a garnet build up to a given step, or "module" e.g. to run floorplanning on `tile_array` in the context of `full_chip` you would do
```
test_module.sh full_chip tile_array --steps init
```
When the script finished, the build environment it had constructed would be lost.
This change allows `test_module.sh` to be optionally sourced, such that the environment remains and more steps can be taken manually e.g. something like
```
test_module.sh full_chip tile_array --steps lvs
echo finished building tile array, now do full_chip floorplan
cd ..; make init
```

make test_module.sh sourceable as well as executable

---

tests/test_app/Makefile
tests/test_memory_core/build_tb.py

self explanatory - some logic was bugged without this fix, making life for @akhileshvb very difficult.

move reinit of lists to within for seed

---

.buildkite/pipelines/pmg.yml
bin/requirements_check.sh

I rewrote(*) the mflowgen pipeline (`pmg.yml`) to use the new hierarchical subgraphs feature in mflowgen, instead of my old test_module hack. It seems to be working fine. You can see the results e.g. here: https://buildkite.com/tapeout-aha/mflowgen/builds/7338
(*) "I rewrote" = Alex dictated and I wrote :)

Subgraphs for buildkite "mflowgen" pipeline

---

global_buffer/design/CG.py
global_buffer/design/SRAM.py
global_buffer/design/clk_gate.py
global_buffer/design/glb_bank_memory.py
global_buffer/design/glb_bank_sram_gen.py
global_buffer/design/global_buffer_parameter.py

Include Taeyoung's intel sram change

Change process to intel for glb design files

---

tests/test_memory_core/build_tb.py

Add code to parse the additional "mode" argument for crddrop nodes in graph to configure the cmrg_mode configuration register. Also merging sparse apps added by @kalhankoul96 to master

New crddrop mapping support and add sparse apps

---

tests/test_memory_core/build_tb.py

Changes to build_tb for VR configuration and regression tests.

Vector accum mapping

---

mapper/netlist_graph.py

This change fixes some issues with camera pipeline

Compute kernel latency and ub_latency kernel naming fixes

---

garnet.py

Turns out that https://github.com/StanfordAHA/garnet/pull/1036 was a little too aggressive in the simplification of the PnR code within garnet. This is why:
Here are all the cases for pipeline_pnr and generate_bitstream_only:
pipeline=False and genbo=False
This will call garnet.place_and_route(load_only=False) which does place and route, but no rescheduling.
Requires one call to PnR.
pipeline=False and genbo=True
This will call garnet.place_and_route(load_only=True) which does no actual placement and routing, it just loads a previous PnR result and the configuration of all the tiles.
Requires one call to PnR.
pipeline=True and genbo=False
This will call garnet.place_and_route(load_only=False), then reschedule_pipelined_app, then garnet.place_and_route(load_only=True). The second …

Fixed the removal of a necessary PnR call

---

tests/test_memory_core/build_tb.py

Adding Sparse Matrix- Dense Matrix matmul with floating point

Adding piece for Sparse Matrix- Dense Matrix matmul with floating point

---

README.md
daemon/test_daemon.py

Removes remaining autoflake errors from daemon code

Lint daemon test

---

copy_formatted_tensor_tiling.py
tests/test_app/waveform_script.py

tensor script
and minnor gantt chart script change

added latest tensor script

---

tests/test_memory_core/build_tb.py
tests/test_memory_core/sparse_app_mappings.py

1. Add software gold generation support for mat_elemdiv
2. Update name of the exponential lut tensor from "exp" to "fp_exp" to match its division counterpart.
3. Added support for generating content for the division lut.

Added support for mat_elemdiv

---

tests/test_app/waveform_script.py

1. update the port name of the crddrop in the waveform rc generation script

crddrop refactor

---

.gitignore
concat_tiles.py
tests/test_memory_core/build_tb.py
tests/test_memory_core/sparse_app_mappings.py

1. Overhaul the collateral directory parsing/dumping code to make it work with Lego
2. Update .gitignore to ignore the dumped collateral
3. Experimental change to the matmul_ijk_crddrop_fp software max to allow it to read gold from lego

Regression refactor

---

mapper/netlist_graph.py
mapper/netlist_util.py

Fix the latency update of reg chain. Now can disable MANUAL_PLACER but still enable IO2MEM_REG_CHAIN and MEM2PE_REG_CHAIN

Hotfix of latency update for resnet manual placement

---

tests/test_app/Makefile

Add verilator to list of valid tools in makefile error msg

Add verilator to list of valid tools in makefile error msg

---

memory_core/pond_core.py

Adds a flag to lake_top so we can flush the regfile in Pond - [This PR](https://github.com/StanfordAHA/lake/pull/216)

enable the flush in pond regfile

---

garnet.py
tests/test_memory_core/build_tb.py

Corresponding AHA branch is here: https://github.com/StanfordAHA/aha/tree/zircon-non-split-fifos

Put flags around non-split-fifo code

---

garnet.py
global_buffer/design/glb_mu_transl.py
global_buffer/design/glb_tile.py
global_buffer/design/global_buffer_parameter.py
matrix_unit/cgra2mu_ready_and.py

1. Ready-valid loopback for `mu2cgra_valid`/`cgra2mu_ready`
2. Fixing issue with unified MU-GLB ifc that would cause GLB to sometimes return data to wrong channel
3. Fix bug with emitting flush from output IOs for MU apps

HW bug fixes for zircon hello world

---

garnet_amber.py
mflowgen/common/rtl/gen_rtl.sh

Oops my recent aha change broke the garnet CI pretty hard.
This should fix it.
It's a tiny change but kinda crucial so I'm going to go ahead and push it through...

Git restore hotfix

---

global_buffer/design/glb_addr_gen.py
global_buffer/design/glb_cfg.py
global_buffer/design/glb_load_dma_E64_MB.py
global_buffer/design/glb_step_counter.py
global_buffer/design/glb_store_dma_E64_MB.py
global_buffer/design/glb_tile.py
global_buffer/gen_global_buffer_rdl.py
passes/clk_pass/clk_pass.py

Bank toggle mode for GLB tile. 
Also has fix for clk_pass through in MEM tile

Glb bank toggle/MEM clk pass through fix 

---

tests/test_app/lib/map.c
tests/test_app/lib/parser.c
tests/test_app/lib/parser.h
tests/test_app/tb/environment.sv
tests/test_app/tb/kernel.sv

Get scale layer works with bank toggle mode in behavior mu test.
Corresponding AHA PR: https://github.com/StanfordAHA/aha/pull/2063

Zircon apps mapping

---

tests/test_app/tb/environment.sv

Add detailed performance tracking for all apps. Cycle counts for the app run time, config time, and time to write data to GLB can now be seen in the AHA regression summary reports.
Corresponding AHA PR: https://github.com/StanfordAHA/aha/pull/2079

Zircon performance tracking

---

garnet.py
mapper/netlist_util.py
tests/test_memory_core/build_tb.py

Corresponding AHA PR: https://github.com/StanfordAHA/aha/pull/2084

Mu io auto route
