StanfordAHA/garnet

common/util.py

Addresses issue in https://github.com/rsetaluri/magma_cgra/issues/22#issuecomment-405343353
Basically, on a shared machine environment we run into an issue where if the file was created by another user, we can't edit it. This uses python's `tempfile` library to create a new, unique temporary directory for the temporary file.

Compile using a fresh temporary directory to avoid conflicts on shared machines

---

common/util.py
test_cb/test_regression_ncsim.py

This prevents the tests from failing when testing on a local machine where ncsim isn't available. Ideally we can remove this once we get the `iverilog` version of the test (since we can expect this to be installable in broader contexts).

Skip test if irun not available

---

.travis.yml
README.md

@alexcarsello @ankita0805 after this is merged, you can drop the `export` commands that use an old version of coreir. We can update the shared kiwi installation to be the latest master.

Install latest coreir version now that master is fixed

---

cb/cb_magma.py
simple_cb/simple_cb_magma.py
test_common/gold/config_register.json
test_common/test_config_register.py

There's now a distinct interface for synchronous and asynchronous resets.
I removed the explicit `reset=...` because the reset signal is automatically wired in the backend, so you don't need to specify it unless you want something different than the default behavior.

Update cb/simple_cb for upstream mantle changes

---

.travis.yml
common/irun.py
common/util.py
conftest.py
test_cb/test_cb_regression.py
test_cb/test_cb_regression_ncsim.py
test_common/test_config_register.py
test_simple_cb/test_simple_cb_regression.py

After inspecting the coverage report at coveralls, it seems like it was only reporting for the `cb` module.
I've updated the check to report for all of them by fixing the invocation of `pytest` on the travis script.
Not sure how this will affect our coverage report (might go down), but this would be good motivation to fix any missing coverage problems.

Fix coverage invocation

---

cb/cb_magma.py
simple_cb/simple_cb_magma.py

`==` is now overloaded! Also changed it from `uint` to `bits` since that's the type of the config_addr. This doesn't matter since they're sub types (I checked by running the tests with `m.bits` and `m.uint`), but it's a bit more explicit when reading the code.

Use eq operator

---

common/irun.py
test_cb/test_cb_regression.py
test_global_controller/test_global_controller_genesis2.py
test_mem/test_mem_genesis2.py
test_simple_cb/test_simple_cb_regression.py

This branch was stale, forgot to pull it in. It updates our tests to use fault's new `compile_and_run` interface. Also enables the test for the simple_cb by implementing a simple class to map the renamed ports.

Fault compile and run

---

.gitignore
test_memory_core/sram_stub.v

Here is an update to the sram stub that I believe makes it match the behavior of the IP we're using. Basically, it shouldn't perform the read if WEN is active.
I'm planning to add some units tests for this module once we've merged this in (so we can also run the tests against the IP to make sure our understanding is correct).

Update sram stub to match semantics of IP

---

cb/cb.py
common/model.py
common/regression_test.py
test_cb/test_cb_regression.py
test_simple_cb/test_simple_cb_regression.py

Here's an attempt to remove more boilerplate from the regression tests (motivated by https://github.com/StanfordAHA/garnet/issues/14).
The logic to zero the inputs is moved into the fault.tester.
The logic to check consistency of the interfaces is moved into `common/regression_test.py`

Refactor regression tests

---

test_common/gold/config_register.json

Magma changed it's logic for generating constant values, which meant a change in the gold file.
In this case, one constant value was packed into a single `coreir.const` instance (it originally was defined using `corebit.const` instances with just 0 and 1). Another was a change to the name of the generated constant instance.

Update config_register.json for upstream magma change

---

cb/cb.py
common/configurable_model.py
common/testers.py
memory_core/memory_core.py
setup.py
simple_cb/simple_cb.py
test_cb/test_cb_regression.py
test_common/test_config_register.py
test_memory_core/test_memory_core_genesis2.py

* Support for None values were removed.  Changed the functional models
to use fault.UnknownValue (X) by default. Then the test logic was
updated to expect `AnyValue` on the outputs when they are
unspecified/undefined. For example, the test expects AnyValue for
outputs of the memory during the reset sequence since the values are
undefined.
* bit_vector `as_uint()` instead of `as_int()`, since `as_int()` returns
the signed representation now (before it depended on whether the signed
flag was set on initialization).
* bit_vector `as_uint()` instead of `.unsigned_value` since the API
has changed to be consistent with the `as_int` pattern.
* Explicitly cast lists to BitVectors for tests since the BitVector
`==` operator no longer does implicit conversions.

Update code based on upstream bv/fault changes

---

common/config_register.py
common/util.py
test_common/gold/config_register.json
test_common/test_config_register.py

Magma changed it's `str` logic for anonymous values, also the mantle.coreir.register now uses a specialized implementation that maps the n-bit primitive (rather than generating a bunch of DFFs)

Update config register gold

---

global_controller/README.md
global_controller/global_controller.py
test_global_controller/test_global_controller.py

Adds the functional model for the global controller and the accompanying tests.
The global controller differs pretty significantly from the other modules in that for many of the opcodes, multiple sequences of outputs need to be modeled. To do this, I model the outputs as lists of BitVectors, where each element of an output list is the value of that output in a given clock cycle.
Some things regarding clock switching aren't completely modeled here:
- For clock switching, you just write to a clock select register. There are no clock inputs or outputs in the functional model.
- Clock switch delay select. You can select whether at the end of a clock switch, the clock is ungated on a rising or falling edge in the actual hardware. Again, in the functional model, this is just a 1 bit register …

Gc functional model

---

README.md

It's available on pip, no longer need submodule instructions.

Update CoSA install instructions

---

column/column_magma.py
common/mux_with_default.py
common/mux_wrapper.py
common/side_type.py
common/zext_wrapper.py
conftest.py
generator/configurable.py
generator/const.py
global_controller/global_controller_magma.py
interconnect/interconnect_magma.py
memory_core/memory_core_magma.py
pe_core/pe_core_magma.py
requirements.txt
simple_cb/simple_cb_magma.py
simple_cb/simple_cb_magma_old.py
simple_sb/simple_sb_magma.py
test_simple_cb/test_simple_cb_regression.py
test_top/test_top_magma.py
tile/tile_magma.py
top/top_magma.py

This PR primarily adds the ability for the global controller to read configuration state from the CGRA.
Each feature within a tile has a read_data output, which is equal to the register corresponding to the register field within config_addr. If a feature has only 1 feature, there is no mux... it is wired directly to the read_data output.
At the tile level, read_data outputs from each feature are muxed together. However, since we want to output 0 here, I've introduced a "mux with default" generator. It behaves like a mux, except it also has an enable signal. For the mux to output one of the inputs, its enable signal must be high and the select bit must be valid (SEL < NUM_INPUTS). The enable signal here is the config_read input to the tile.
At the column level, each tile's read_data output …

Add read data

---

.travis.yml
test_common/test_configurable_model.py
test_common/test_model.py

I updated to Python 3.7 locally and ran into some minor issues in the tests.
I tried adding Python 3.7 to the travis script, but there were some issues that I didn't think were worth pushing on. Mainly, https://github.com/travis-ci/travis-ci/issues/9815 says that it's not supported in the default configuration, so we can wait to enable the python 3.7 tests until Travis supports them directly. If we'd want to use it now, we have to enable sudo and use the xenial distribution, which I think may cause issues with various Ubuntu installed dependencies that will have to be worked out.
Instead, here's a change to the tests that maintains compatibility with python 3.6, but allows the tests to pass locally for me on 3.7.
The `repr` string for Error messages has changed (dropped the trailing …

Refactor repr based tests

---

cb/cb_genesis2.py
common/genesis_wrapper.py
common/testers.py
memory_core/memory_core_genesis2.py
setup.py
simple_cb/simple_cb_genesis2.py
test_cb/test_cb_genesis2.py
test_cb/test_cb_regression.py
test_memory_core/test_memory_core_genesis2.py
test_simple_cb/test_simple_cb_genesis2.py
test_simple_cb/test_simple_cb_regression.py
test_simple_pe/test_simple_pe_magma.py

Depends on https://github.com/leonardt/fault/pull/33, https://github.com/leonardt/fault/pull/32, and https://github.com/leonardt/fault/pull/31.
Needed these changes to get the tests passing locally with the latest fault master branch. Once the above pulls are merged, we can do a release, and make sure the tests in this repo still pass with the latest changes.
Opening this PR to track this, but we'll need to wait for the fault merges before this passes.

Updates for fault 0.23 release

---

generator/configurable.py
memory_core/memory_core_magma.py
pe_core/pe_core_magma.py
simple_cb/simple_cb_magma.py
simple_sb/simple_sb_magma.py
test_simple_cb/test_simple_cb_magma.py
tile/tile_magma.py

-Adds config_en/feature address decode logic in tile to allow for writing to config regs
-Connects config_en to write port of each config register
Still TODO:
SRAMs not yet R/W-able over config bus. To make this happen, we'll need to add a way for cores to have "extra" features and communicate this information to the tile.

Add config enable

---

column/column_magma.py
generator/generator.py
global_controller/global_controller_magma.py
interconnect/interconnect_magma.py
memory_core/memory_core_magma.py
pe_core/pe_core_magma.py
tile/tile_magma.py
top/top_magma.py

This PR primarily adds functions to column and tile to make the global signal management transformations.
There is now a column base class, with ColumnFanout and ColumnMeso classes that inherit from it to implement two different global signal distribution schemes.
I've also added a remove_wire function to the generator base class, as this was necessary to implement the transformations for combining the read_data signals down a column.
Additionally, in the pe and memory cores, there were many underlying signals that weren't connected (clk_en, wen_in, ren_in). I filled in some of those connections.
In Tile, I've added a function that takes in an input port adds a corresponding output port to pass an input signal through the tile. I've also added a function to do the read_data reduction in …

Global signal column

---

common/dummy_core_magma.py
common/testers.py
setup.py
simple_sb/simple_sb_magma.py
simple_sb/simple_sb_model.py
test_memory_core/test_memory_core_genesis2.py
test_pe_core/test_compute_unit.py
test_pe_core/test_pe_core.py
test_simple_cb/test_simple_cb_magma.py
test_simple_sb/test_simple_sb_magma.py
test_simple_sb/test_simple_sb_magma_no_model.py
test_tile/test_tile_magma.py

Add optional registers to buffer the output of each mux in the switchbox. Right now the test fails because the model has not been updated to reflect these changes but a basic test called test_simple_sb_magma_no_model does pass. Before finalizing this change I plan to make the no-model test more comprehensive. I will also edit the model-based test to at least configure the optional buffers to not buffer so that the test works like before.

Add registers

---

.travis.yml
README.md
test_simple_pe/test_simple_pe_magma.py

`z3` was easier to install on CentOS which we are using for ee272. I don't think anyone cares about which solver is used (let me know otherwise), so this changes the CoSA related tests to use the `z3` solver. It also updates the README with the setup instructions.

Switch msat to z3 for CoSA test

---

interconnect/circuit.py
interconnect/cyclone.py
interconnect/interconnect.py
test_interconnect/test_circuit.py
test_interconnect/test_cyclone.py
test_interconnect/test_interconnect.py

This PR add a pass to the interconnect graph to insert pipeline registers. Per Mark's request, the pass interface allows user to insert pipeline registers on a particular side and track of a SB. This ability reduces the routing area if registers are not inserted everywhere.
Test:
Sequential poke and peak at different clock cycles to test the register mux selection.

Add pipeline registers

---

common/transform.py
interconnect/circuit.py
interconnect/global_signal.py
interconnect/interconnect.py
test_interconnect/test_interconnect.py

This PR mainly deals with global signal wiring:
1. Introduce refactored version of signal transformations (`common/transform.py`). Previously it was nested in the `tile/tile_magma.py` . The new functions introduced allow more generic version of passes through garnet infrastructure.
2. Create different pass functions, namely `apply_global_fanout_wiring`, and `apply_global_fanout_wiring`, that take `Interconnect` object and connect global signals within the interconnect object. An example is shown in the test:
https://github.com/StanfordAHA/garnet/blob/4bae028704c3c986db55f5eddd56d3b431b204c4/test_interconnect/test_interconnect.py#L91-L98
Both `Fanout` and `Meso` are tested with various interconnect configuration.
I will start to clean out deprecated old once the interconnect is fully …

Interconnect global signal

---

interconnect/circuit.py
interconnect/cyclone.py
interconnect/interconnect.py
test_interconnect/test_interconnect.py

This PR adjusts the module names to make the produced verilog more readable. Previously it relied on the cryptic annotation that only my PnR tools understands.
Since the unification is fixed, I also removed the hack that changed the module name to avoid conflicts.
That being said, there is still a long way to go to produce more readable verilog.

Interconnect Rename

---

generator/configurable.py
generator/generator.py
test_generator/gold/core_instance_name.v
test_generator/test_instance_name.py

Add support for the `name` parameter to the `__init__` method of
`Generator`. This allows the user to override the default naming scheme
for instances.
Set the config register instance names inside the dummy core generator.
@Kuree Can you review how this is done and let us know if it makes sense? This should give you a way to provide hints to the system about how you want instances to be named in the generated verilog. Also let us know if there's more/different functionality that you require.

Adds simple example for setting instance names

---

common/mux_wrapper.py
interconnect/circuit.py

This PR renames mux, registers, and tile level instance names so that it's easier to debug. Notice that there are still some circuits' name not readable, notably decode. Since I don't directly interact with these decode modules, I just leave them as it is.

Improve circuit instance names for better debugging

---

generator/from_verilog.py

Since the CoreIR backend can now include verilog completely we can
use DefineFromVerilog instead of DeclareFromVerilog.

Change DeclareFromVerilog to DefineFromVerilog

---

common/core.py
interconnect/circuit.py
memory_core/memory_core_magma.py
test_interconnect/test_interconnect_cgra.py

This PR supports multiple features in the Core object. It's achieved by "port aliasing" to unify the `config` and `read_config_data` access from the tile level. An example is shown below:
```Python
for idx, core_feature in enumerate(self.__features):
self.add_port(f"config_{idx}", magma.In(ConfigurationType(8, 32)))
core_feature.ports["config"] = self.ports[f"config_{idx}"]
```
If you access `core_feature.ports.config` from the tile level, it's accessing the memory core top level port config_idx. This avoids the problem where a child generator has to be connect within the parent, not outside the parent.
An example can be seen in the memory wrapper. I've tested the memory with SRAM mode. The only problem is that `read_data_sram` doesn't work. This is due to the complicated implementation …

Interconnect feature

---

.travis.yml

Looks like this is no longer necessary, still have no idea what was going on. I suspect some package we were installing was messing with our environment.

Remove filecmp issue workaround

---

tests/test_global_controller/test_global_controller_verilog_sim.py

Fixes global controller ncsim test, pending resolution of rsetaluri/gemstone#1. It was failing because the paths to genesis files were never adjusted after the repo was reorganized.

Repair tests

---

requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

`archipelago` is a python interface for two native Python bindings:
1. `pythunder` for placement: https://pypi.org/project/pythunder/
2. `pycyclone` for route: https://pypi.org/project/pycyclone/
`archipelago` is written purely in Python and can be installed via
```
pip install archipelago
```
This PR mainly replace all the manual routes with the automatic pnr function call.
```
placement, routing = pnr(interconnect, (netlist, bus))
```

Use archipelago for pnr

---

Makefile
README.md

For your consideration:
* I added a couple of lines to the README, see diff for details
* I wanted a "make clean" so I built a Makefile; and then since I already had the makefile I added rudimentary targets for test, pytest, build and help.
Default "make" command with no args does this:
```
$ make
To test your installation simply do:
pytest
For help do this:
python garnet.py --help
Example build:
python garnet.py --width 2 --height 2
```
"make clean" does this:
```
$ make clean
Building cleanup dir old_design_190422_0858/...
Moving core Genesis files...
mv genesis.log genesis_work/ genesis_raw/ genesis_verif/ genesis_synth/ 
genesis_vlog.vf genesis_vlog.synth.vf genesis_vlog.verif.vf genesis_clean.cmd 
old_design_190422_0858/
Moving build-specific Genesis files...
mv MEMmemory_core …
```

Readme and cleanup

---

requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

Update the new IO semantics so that we can add IOs to the north side only. Need it to unblock Taeyoung.
I'll change `canal` remote once it gets approved there: https://github.com/StanfordAHA/canal/pull/3

Use the new semantics of canal io creation

---

global_controller/genesis/global_controller.svp

The fixes a bug in the recent modifications to the global controller. Logic was inserted to choose between instructions coming in over JTAG and those coming in through AXI. The old logic only accepted a JTAG instruction when an AXI instruction was also present, which is not correct. This fixes that.
@kong0329 also the op_axi wire is floating. What is it supposed to be connected to?

make it so that jtag can control GC regardless of axi

---

peak_core/peak_core.py

This is a quick and dirty way to cache all the PE and magma circuit generation from peak. In the long run this should be handled in lassen.

Add pe caching

---

.travis.yml
.travis/genesis_env.sh
.travis/run.sh

Pros:
1. Same environment as `GarnetFlow`
2. Latest `Python` (3.7.3), `verilator` (4.010), `gcc` (8.3). No need to resort to `miniconda` or other ppa to have latest `verilator`.
3. Easy to reproduce locally since it's the same environment.
Cons:
Can't think of any.
This will also unblock @kong0329 to merge in global controller tests. See: https://github.com/StanfordAHA/garnet/issues/241.

Use docker container to run the tests

---

power_domain/pd_pass.py

Before:
After:
Due to the newly introduced hashing function on the `PortReference`, i.e. using owner names, the runtime to generate `32x16` is about 2.5 minutes. That is, we increase lots of overhead to ensure the caching is safe.
This PR along with the improvement in magma (https://github.com/phanrahan/magma/pull/397) will bring down the runtime to less than 2 minutes again.
What happened here:
- The `replace` itself is <img src="https://latex.codecogs.com/svg.latex?O%28n%29">, where `n` is the number of connections.
- Each mux in the switch box will be replaced using `replace`, which effectively makes it <img src="https://latex.codecogs.com/svg.latex?O%28n%5E2%29">, assuming each mux has a fixed number of connections.
How to fix them:
- By understanding how these muxes are created, we …

Speed up the garnet creation by 30%

---

tests/AN2D0BWP16P90.sv
tests/AO22D0BWP16P90.sv
tests/test_interconnect/test_interconnect_cgra.py
tests/test_interconnect/test_reset.py

Add verilog files needed for Fault tests. Add the verilog pointers to the test files.

Verilog pointers for Fault tests

---

.travis.yml
collateral_pass/config_register.py
requirements.txt
tests/test_collateral_pass/test_config_reg.py

Per @thenextged's request, this pass dumps all the touchable registers used in the interconnect. We will use this collateral pass to test soc and global controller.

Add a pass to extract all interconnect touchable registers

---

global_controller/genesis/tap.svp
tests/test_global_controller/test_global_controller_verilog_sim.py

Change the TAP wrapper in the JTAG controller to use Cadence ChipWare IP for the TAP state machine rather than the Synopsys DesignWare IP. From what I can tell, the two IPs appear to be identical. Since we are using Cadence tools for synthesis and P&R, using ChipWare makes it so that I don't have to maintain a separate DC flow just for the JTAG/global controller.

Use Cadence chipware IP instead of Synopsys DesignWare

---

memory_core/genesis_new/fifo_control.svp
memory_core/genesis_new/linebuffer_control.svp
tests/test_interconnect/test_interconnect_cgra.py

addressing #259  - valid is now combinational (was previously registered) with real dependence on the wen signal. the ren_to_fifo goes high at depth-1 because we register the first input to the output so it is ready to be consumed downstream. The ren won't be asserted again, so the fifo data should remain until it is forcibly pushed downstream.

Mem core fixes

---

memory_core/memory_core.py
memory_core/memory_mode.py
tests/test_interconnect/test_interconnect_cgra.py
tests/test_memory_core/test_memory_core.py

This allows other modules to manipulate the memory mode without importing from the functional model module.

refactor out memory mode

---

global_buffer/genesis/global_buffer_int.svp
global_buffer/genesis/host_bank_interconnect.svp
global_buffer/genesis/sram_gen.svp

Previously, I implemented all pipeline registers as flipflop w/o reset.
I think it is better for `rd_data` register to go to `0` at reset, so I changed it.
Also, in this PR, I removed unnecessary `timescale 1ns/100fs` code in `sram_gen.svp`

Change global buffer data pipeline register to have reset

---

global_controller/genesis/global_controller.svp
tests/test_global_controller/genesis/test.svp

This is a minor change about `soft_reset_delay` register.
Previously, `soft_reset` is asserted for one cycle and `soft_reset_delay` register just decided the delay between `cgra_start` and `soft_reset`.
With this PR, `soft_reset` is asserted when `cgra_start` register is written, and `soft_reset_delay` determines how many cycles it would be asserted.
(if `soft_reset_delay` is 0, it is asserted for one cycle. If `soft_reset_delay` is `n`, `soft reset` is asserted for `n+1` cycle.)

Replace soft_reset_delay with soft_resetting_time

---

.gitignore
memory_core/memory_core_magma.py
requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

this Ors the config_write and config_read for each SRAM port to be the respective config_en, then ORs together all config_read and config_write and sends to underlying config_read and config_write port on the memory core interface

Fix sram config en

---

cgra/tile_id_pass.py
cgra/util.py
tile_id_pass/tile_id_pass.py

A new pass on the CGRA to perform the tile_id connections in a slightly different way.
Because we are creating a fully abutted grid of tiles, there are no channels between the tiles to place tie cells to tie the tile_id pins to the correct constant values. we could assign tile_id values within the tiles themselves, but this would uniquify every single tile, which would be very bad for our physical design flow, because we'd have to place and route each tile individually given our current setup. 
This pass gets around both of these issues by giving each tile a set of constant outputs: hi (constant 1) and lo (constant 0). During tile level place and route these hi and lo pins will be interleaved with the tile_id pins as follows:
| hi[0] | id[0] | lo[0] | id[1] | hi[1] | id[2] | lo[1] | id[3] …

Tile id pass

---

global_buffer/genesis/io_address_generator.svp
global_buffer/genesis/io_controller.svp
tests/test_global_buffer/verilator/test_global_buffer_int.cpp

In some corner cases, extra `cgra_start` signal can be asserted again even before `cgra_done` signal is generated.
Previously, I just ignored such cases.
In this PR, I give `cgra_start` a priority, so if `cgra_start` signal is asserted again, it will start feeding data again.

Give start signal priority

---

.travis.yml
tests/test_pe_tile_formal/problem.txt
tests/test_pe_tile_formal/source.vlist
tests/test_pe_tile_formal/test_pe_tile_interconnect.py

This pull requests adds a test for `pytest` to run that loads in the generated Verilog and checks a few basic properties of the PE Tile (instantiated as the top module). The properties are generalizations of ttests 4, 5, 6 and 7 from this [testbench](https://github.com/StanfordAHA/garnet/blob/tapeout/tapeout_16/gls/tb_Tile_PE.v).
These are performed at the RTL level, but we will soon try to check the properties on the final netlist with power/ground information.
Ideally, we will also continue to add more formal property verification to Travis. If this makes the Travis build time too long, I'm happy to set it up on BuildKite or elsewhere instead.
@ankita0805

Add CoSA problems for Garnet PE Tile Interconnect

---

global_controller/genesis/jtag.svp
global_controller/genesis/tap.svp

Per @zamyers request, make the JTAG IDCODE more distinctive for easier chip bringup.

Make JTAG IDCODE 650

---

peak_core/peak_core.py
requirements.txt

Removes dependency on `auto_assembler`

Migrate to peak assembler type

---

mflowgen/Tile_MemCore/cadence-innovus-plugins/configure.yml
mflowgen/Tile_MemCore/cadence-innovus-plugins/plugins/pre_place.tcl
mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/cadence-innovus-plugins/configure.yml
mflowgen/Tile_PE/cadence-innovus-plugins/plugins/pre_place.tcl
mflowgen/Tile_PE/construct.py
mflowgen/glb_tile/cadence-innovus-plugins/configure.yml
mflowgen/glb_tile/cadence-innovus-plugins/plugins/pre_place.tcl
mflowgen/glb_tile/construct.py
mflowgen/glb_top/cadence-innovus-plugins/configure.yml
mflowgen/glb_top/cadence-innovus-plugins/plugins/pre_place.tcl
mflowgen/glb_top/construct.py

The way we were adding well taps and end caps in the pre_place plugin was technology independent. With this PR, well tap and end cap insertion have been moved to tcl procs in the ADK, which the plugin calls.

Tapeout taps and caps

---

garnet.py
mflowgen/Tile_MemCore/rtl/gen_rtl.sh
mflowgen/common/rtl/gen_rtl.sh

Added Added the flag --standalone to garnet.py. If this flag is specified IO cores are not added to the CGRA fabric.
Also renamed `no_sram_stub` option to `no-sram-stub`.

Garnet top script enhancements

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/common/rtl/configure.yml
mflowgen/common/rtl/gen_rtl.sh
mflowgen/tile_array/construct.py

Small PR to add tile array height, width, and interconnect_only params to common rtl generation node.
Setting the interconnect_only param generates only the array of tiles without the global buffer. When we set this, we can generate the 2x2 array of tiles we want for timing constraints development and testing.

Mflowgen rtl params

---

mflowgen/common/custom-power-leaf/outputs/power-strategy-dualmesh.tcl

Small update for leaf-level power strategy to extend M8 power stripes to design boundary. This allows the M8 power grid to connect by abutment between macros.

Extend leaf-level power straps to design boundary

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/glb_tile/construct.py
mflowgen/glb_top/construct.py
mflowgen/tile_array/construct.py

For each Innovus node, there is an order parameter that defines the order in which the subscripts of that node are run (e.g., floorplan, adding end caps).
Previously, the order parameter had to be defined explicitly, listing out everything in a super long string. The latest mflowgen commit turns this into a normal-looking Python list. Now you can just call "append()" on the order, etc.
This pull request makes this change to each block's construct.py to insert the "add-endcap-welltaps.tcl" after wherever "floorplan.tcl" is in the Innovus init node.

turn order params into a list

---

mflowgen/glb_top/construct.py
mflowgen/tile_array/construct.py

Fix bug in #435 that left out dont_touch for init order param in hierarchical blocks.

Add back dont_touch script to init order param

---

mflowgen/Tile_MemCore/construct.py
mflowgen/glb_tile/construct.py

This PR connects the sram db files from gen_sram_macro to the genlibdb nodes in both the memory tile and the glb tile. In conjunction with [this mflowgen PR](https://github.com/cornell-brg/mflowgen/pull/16), this will ensure that the SRAMs are properly linked when extracting the timing models for these blocks.

Sram genlibdb

---

tbg.py

`tbg.py` is really testing the `Interconnect` rather than `Garnet`, so this PR makes that a bit more explicit, primarily in order to match with the physical design flows. 
It's done in the most minimal way for now, and defines from `garnet.v` instead of `garnet_stub.v` to avoid breaking other code that calls `tbg.py` (e.g. CI scripts). 
`stub_filename` is now unused inside the testbench generation, it copies things over to `Interconnect.*` instead of `Garnet.*`, and the final testbench is `Interconnect_tb.sv` as generated by fault.

retarget tbg to Interconnect top module

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py

This PR changes how the genlibdb order param is modified to insert our `set_case_analysis` constraints. Instead of overwriting the existing order param, we insert the script we want at a known point in the order.

Mem/PE Tile genlibdb order param

---

mflowgen/common/init-fullchip/outputs/route-bumps.tcl

route_bumps.tcl had direct references to the design name "pad_frame" which made it break when used in the full chip flow.

remove hardcoded design name from route_bumps.tcl

---

global_buffer/Makefile
global_buffer/global_buffer_magma.py
global_buffer/global_buffer_magma_helper.py
global_buffer/global_buffer_main.py
global_buffer/rtl/glb_bank.sv
global_buffer/rtl/glb_bank_ctrl.sv
global_buffer/rtl/glb_bank_memory.sv
global_buffer/rtl/glb_core.sv
global_buffer/rtl/glb_core_load_dma.sv
global_buffer/rtl/glb_core_pc_dma.sv
global_buffer/rtl/glb_core_pc_router.sv
global_buffer/rtl/glb_core_proc_router.sv
global_buffer/rtl/glb_core_sram_cfg_ctrl.sv
global_buffer/rtl/glb_core_store_dma.sv
global_buffer/rtl/glb_core_strm_mux.sv
global_buffer/rtl/glb_core_strm_router.sv
global_buffer/rtl/glb_core_switch.sv
global_buffer/rtl/glb_dummy_end.sv
global_buffer/rtl/glb_dummy_start.sv
global_buffer/rtl/glb_tile.sv
global_buffer/rtl/glb_tile_cfg.sv
global_buffer/rtl/glb_tile_cfg_ctrl.sv
global_buffer/rtl/glb_tile_int.sv
global_buffer/rtl/glb_tile_pc_switch.sv
global_buffer/rtl/global_buffer.filelist
global_buffer/rtl/global_buffer.sv
global_buffer/rtl/global_buffer_pkg.svh
global_buffer/systemRDL/rdl_models/glb.rdl

Instead of instantiating `global_buffer` module with parameters concatenated, I dumped package file with all parameters defined in that file.
I think it is preferred for two reasons.
1. systemverilog `struct` types are defined in a package file, and they also use parameters. However, there is no way to pass parameters to package file.
2. This method doesn't require adding parameters to all rtl modules and passing them when instantiating submodules.  
3. `systemRDL` (an addressmap generation file that I am working with Gedeon) currently does not support parameter passing. With this way, I can also export a file with parameters defined, which can be later appended into `systemRDL` file.
If @rsetaluri think this is fine, I prefer to use this way of passing parameters.

Export parameters to package files which systemverilog and systemRTL use

---

cgra/util.py
cgra/wiring.py
garnet.py
requirements.txt

As requested, I moved `parallel_meso_wiring` from `canal` to `garnet`.
After it is merged, `par_meso` branch in `canal` can be deleted.

Move parallel config meso wiring from canal to garnet

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/glb_tile/construct.py

Removes old code that manually added 'add-endcaps-welltaps.tcl' to the init order for multiple mflowgen flows. No longer necessary because it's part of the default init order now.

Remove duplicate endcap-welltap steps

---

global_buffer/dump.tcl
global_buffer/rtl/glb_core_switch.sv
global_buffer/testbench/glb_test.sv
mflowgen/glb_tile/constraints/constraints.tcl
mflowgen/glb_tile/construct.py

This PR basically improves channel selection controller within `glb_tile` regarding `stall` signal.
There are three different packets in `glb`; soc packet, parallel configuration packet, and cgra data stream packet.
`stall` signal should not affect soc packet channel and parallel configuration channel.
Previously, combinational logic interprets packet information on the fly and decide whether to stall or not, but I think It causes timing violation.
Now, `glb_tile` has separate channels for each of them and soc packet and parallel configuration channel are not stalled, while cgra data channel is stalled.
Selection among channels only occur at the very last.

Change global buffer tile rtl for timing.

---

mflowgen/global_controller/construct.py

The GLC was missing the PWR_AWARE param. It needs it because it shares its power strategy with the PE and memory tiles.

Add pwr_aware param to glc flow

---

mflowgen/Tile_MemCore/constraints/constraints.tcl
mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_MemCore/custom-init/outputs/floorplan.tcl
mflowgen/Tile_PE/constraints/constraints.tcl
mflowgen/Tile_PE/construct.py
mflowgen/common/power-domains/configure.yml
mflowgen/common/power-domains/outputs/dont-touch-constraints.tcl
mflowgen/common/power-domains/outputs/mem-add-endcaps-welltaps-setup.tcl
mflowgen/common/power-domains/outputs/mem-constraints.tcl
mflowgen/common/power-domains/outputs/mem-load-upf.tcl
mflowgen/common/power-domains/outputs/mem-power-switches-setup.tcl
mflowgen/common/power-domains/outputs/pd-mem-floorplan.tcl
mflowgen/common/power-domains/outputs/pd-pe-floorplan.tcl
mflowgen/common/power-domains/outputs/pe-add-endcaps-welltaps-setup.tcl
mflowgen/common/power-domains/outputs/pe-power-switches-setup.tcl
mflowgen/common/power-domains/outputs/upf_Tile_MemCore.tcl

This PR includes following updates:
- All scripts for Mem tile power aware flow
- Updates to PE and Mem tile power aware flow with hierarchies flattened (flatten_effort=3)
- Clamping logic in the SB/CB is maintained but the rest of the logic is flattened
- GLS passing with flattening
- 2-4 random DRCs 
- LVS clean
Remnant Updates:
- Trim M8 VDD_SW from the edges
- Tie_hi/lo cells handling for tile_id

Power Domains Flow for Flattened PE & Mem Tiles

---

tests/test_peak_core/test_pe_config.py

The peak description of lassen has changed.
See: https://github.com/StanfordAHA/lassen/pull/169.

Remove 16bit multiplier from data gate test

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/common/custom-power-leaf/outputs/power-strategy-dualmesh.tcl
mflowgen/common/power-domains/configure.yml
mflowgen/common/power-domains/outputs/mem-add-endcaps-welltaps-setup.tcl
mflowgen/common/power-domains/outputs/pd-generate-lvs-netlist.tcl
mflowgen/common/power-domains/outputs/pe-add-endcaps-welltaps-setup.tcl

This PR includes following updates:
- VDD_SW M8 stripe is pulled back such that it's not abutted across tiles, so every tile can be individually turned on/off
- LVS Softcheck fixes for PE/memory tile for unconnected tap cells substrate
- Update LVS netlist generation to remove VDD_SW port from top PG ports
- DRCs are random DRCs
- LVS is clean

PE & Memory Tile M8 VDD_SW trimming & tap cells connection

---

mflowgen/full_chip/construct.py
mflowgen/full_chip/glb_top/get_glb_top_outputs.sh
mflowgen/full_chip/global_controller/get_global_controller_outputs.sh
mflowgen/full_chip/tile_array/get_tile_array_outputs.sh
mflowgen/glb_top/glb_tile/get_glb_outputs.sh
mflowgen/tile_array/Tile_MemCore/get_Tile_MemCore_outputs.sh
mflowgen/tile_array/Tile_PE/get_Tile_PE_outputs.sh

- Use verilog instead of spice from blocks to avoid the single-bit bus issues we dealt with before
- Pass the SRAM spice for the blocks up to the top level

fixes for full_chip lvs

---

global_buffer/rtl/glb_bank.sv
global_buffer/rtl/glb_bank_ctrl.sv
global_buffer/rtl/glb_bank_memory.sv
global_buffer/rtl/glb_bank_sram_gen.sv
global_buffer/rtl/glb_core_load_dma.sv
global_buffer/rtl/glb_core_pc_dma.sv
global_buffer/rtl/glb_core_proc_router.sv
global_buffer/rtl/glb_core_store_dma.sv
global_buffer/rtl/glb_tile.sv
global_buffer/rtl/glb_tile_cfg_ctrl.sv
global_buffer/rtl/glb_tile_int.sv
global_buffer/rtl/global_buffer.sv
global_buffer/testbench/glb_test.sv
mflowgen/glb_tile/constraints/constraints.tcl
mflowgen/glb_top/constraints/constraints.tcl

This PR includes update in `constraint` file and RTL to meet timing.
1. There was a timing issue hard to fix regarding SRAM macro. Basically, `sram_gen_array` generates a giant mux of sram macros, which makes it hard to meet timing. I basically added a register right before `sram` instead of `sram_gen_array`.
2. Increase delay to assert interrupt pulse due to increased latency.
3. Increase the number of cycles interrupt pulse is asserted to 4 to meet timing.
4. Add constraints.

RTL changes in global buffer to meet timing.

---

mflowgen/full_chip/glb_top/configure.yml
mflowgen/full_chip/global_controller/configure.yml
mflowgen/full_chip/tile_array/configure.yml

Some last changes to make fullchip LVS work... seems like this was missing from #532 
The files needed for LVS for the block steps in the full chip flow (glb_top, tile_array, global_controller) were being copied to the outputs directory, but since the configure.yml for these steps didn't have the files in it, they weren't being connected to the LVS node.

make block steps in fullchip flow have correct LVS outputs

---

mflowgen/full_chip/custom-init/outputs/place-macros.tcl

For some reason, there were some illegally placed standard cells in the bottom left corner of the fullchip floorplan after init. They made M1 power stripe generation take forever (presumably  because of DRC checking), so I added a line at the end of init to unplace all standard cells.

unplace any std cells placed during init

---

mflowgen/full_chip/constraints/cons_scripts/clocks_4_cgra.tcl

Gets rid of unconstrained paths between tile array, GLB, GLC

Add global controller generated clock constraint

---

mflowgen/common/init-fullchip/outputs/io-fillers.tcl

With the latest SoC RTL, for some reason dc uses the net name "rte_0" for the output of the tie cell that connects to the IRTE port of our PCBRTE cells, which drive the RTE rings for all the pads.
```
//rte_0 is output of TIE_LO cell
TIELBWP16P90 U47 ( .ZN(rte_0) )
//rte_0 connected to PCBRTE pads
PCBRTE_V IOPAD_bottom_RTE_DIG ( .IRTE(rte_0) );
PCBRTE_H IOPAD_left_RTE_DIG ( .IRTE(rte_0) );  
PCBRTE_H IOPAD_right_RTE_DIG ( .IRTE(rte_0) ); 
// rte_0 connected to all tie lo control signals on pad
PRWDWUWSWCDGH_H IOPAD_left_TLX_FWD_CLK_0 ( .I(TLX_FWD_CLK_int_0_), .OEN(
rte_0), .IE(rte_0), .PAD(pad_TLX_FWD_CLK[0]), .RTE(rte_0), .ST(rte_0),
.PU(rte_0), .DS0(n74), .DS1(n88), .PD(rte_0), .SL(rte_0), .DS2(n101)
);
```
This wouldn't be a problem, but there was some old code in our init scripts …

Remove skip routing commands on rte* nets

---

mflowgen/full_chip/constraints/cons_scripts/garnet_constraints.tcl

Changing this to be a false path instead of a multicycle path because of issues with tile_array .lib file

set false path on read_config_data paths

---

mflowgen/full_chip/constraints/cons_scripts/clocks_except_soc.tcl

${idx} wasn't being resolved properly, so I used a `get_clocks` command instead, which got rid of the error from dc.

Fix can't find clock error in soc constraints

---

mflowgen/full_chip/constraints/cons_scripts/garnet_constraints.tcl

This constraint needed -through, since the pin I identified isn't the actual start point

Change interrupt_pulse multicyc path from -from to -through

---

mflowgen/common/fc-netlist-fixing/outputs/netlist-fixing.tcl
mflowgen/full_chip/construct.py
mflowgen/full_chip/custom-lvs-rules/outputs/rules.svrf

Depends on https://github.com/cornell-brg/mflowgen/pull/55
Alex, do you mind testing the new netlist fixing script on the train_5_24_ANALOG_750MHz design? You can just source the script in the final pre-signoff step and then write out an LVS verilog. I can take a look at the verilog to see if it looks right.
You can write the LVS verilog with the following:
```
foreach x $ADK_LVS_EXCLUDE_CELL_LIST {
append lvs_exclude_list [dbGet -u -e top.insts.cell.name $x] " "
}
saveNetlist -excludeLeafCell                   \
-phys                              \
-excludeCellInst $lvs_exclude_list \
<path>.lvs.v
```

various flow fixes for dragonphy

---

mflowgen/common/rtl/configure.yml
mflowgen/common/rtl/gen_rtl.sh

This PR changes the mflowgen rtl node to use the aha docker container to satisfy all of the dependencies needed to generate garnet verilog.
With this change, we hope to greatly improve the reliability of generating garnet RTL by making it easy for everyone to use a consistent snapshot of all garnet dependencies that is already tested and proven to work.
Users who want/need to use their own local python environment can do so by setting the use_container param to false.
Marking this as a draft because I'd still like to be able to capture the local state of the garnet repo and bring that into the docker container, instead of using the pinned version of Garnet. I want to do this because there are many situations in which we make an rtl change in Garnet, and then we need to make accompanying …

Rtl container

---

.buildkite/pipeline_mflowgen.yml
mflowgen/test/test_module.sh
mflowgen/tile_array/custom-init/outputs/floorplan.tcl

Implements a quick 5-minute tile_array test that uses pre-built synthesized RTL to verify cadence-innovus-init scripts. With this addition, we now have a 35-minute test suite of three buildkite checks: PE tile synthesis, mem tile synthesis, and this new tile_array test.
Also available in pipeline.yml, but turned off by default:
* a 60-minute tile_array check that start from pre-built RTL, then synthesizes it.
* a 90-minute tile_array check that starts from scratch and runs through the init stage.
This latest version of test_module has greatly expanded capabilities, including a "--use_cache" option to bring in pre-built steps from a gold cache etc.
```
./test_module.sh --help
Usage: ./test_module.sh [OPTION] <module>,<subgraph>,<subsubgraph>... --steps <step1>,<step2>...
Options:
--branch …
```

Buildkite tile array

---

.buildkite/pipeline_mflowgen.yml

Okay I think I know what went wrong with the tile_array pull.
For now, I think the best thing is to turn off the tile_array test until I can get it sorted. *That's all this pull request does,* is to turn off the problem test.
So when/if these checks complete (back to the original two checks), let's get this merged ASAP so that buildkite runs will finish in finite time again...
Meanwhile I will work in the background to try and get everything running correctly under the new stashed-rtl scheme.

Fix tile array

---

.travis.yml

There are some deprecation warnings in one of the libraries used by garnet. The latest pytest added a braking changes that turns all syntax warnings into error, see [here](https://docs.pytest.org/en/stable/changelog.html#pytest-6-0-0-2020-07-28). This PR pinned pytest to the old version before the dependent library is fixed.

Pin to old pytest since the new one turns syntax warning into error

---

mflowgen/common/rtl/configure.yml
mflowgen/common/rtl/gen_rtl.sh

Tiny fix to prevent mkdir error in rtl node.

add -p to mkdir command in rtl node

---

mflowgen/full_chip/construct.py

After providing the dragonphy db file to synthesis in #627, dc started tying floating dragonphy inputs to 0. This broke the full chip PD flow, because these inputs are connected directly to bumps my the dragonphy_RDL gds that we merge in at the end of the flow. To fix this, I've removed the dragonphy db from the dc step inputs. This makes the dragonphy and unresolved reference, so I've also removed the unresolved reference assertions from the dc step.

Prevent dc from tying floating dragonphy inputs to 0

---

conftest.py

This fixes the out of memory issue on travis.  First, we were using an old API to reset the magma coreir context, using the frontend api fixes an issue where a few references to the context singleton still existed in the coreir backend (the frontend api resets both the context singleton and the coreir backend reference to it).  This prevented it from being properly garbage collected.  Next, rather than rely on the Python garbage collection to clean up the context (will eventually call __del__ to free the memory), we explicitly call the low-level API between each test to ensure we have free memory.  We should add a better API for this in pycoreir, but for now we just access the context pointer directly and call the C-api function.  We hack the logic to avoid a double free by setting the …

Force delete context

---

.travis.yml
.travis/run.sh

The old package `pytest-codestyle` has been deprecated, the newest version should work with pytest 6

Switch to pytest-pycodestyle and unspilt tests

---

memory_core/memory_core_magma.py

Change constructor to SRAMMacroInfo

Set rtsel value properly in tile generation

---

mflowgen/common/rtl/gen_rtl.sh

Makes mflowgen rtl generation using docker container use master branch of lake. This is a hack that should be removed once the problems with the aha tests and Lake are resolved.

insert hack to use master branch of lake when generating rtl for pd

---

requirements.txt

Pins lake to commit hash currently being used in aha so that the master branch is passing travis tests. We can remove this once the compiler issues around the new lake-diet are resolved such that all aha tests pass with the latest version of lake.

Pin lake to pre-lake-diet commit

---

mflowgen/tile_array/construct.py

Removes the assertion that at least 50% of registers are clock gated in the tile array flow. All registers at the tile array top level are pipeline registers for configuration signals, which we cannot clock gate.

remove clock_gate assertion in tile array flow

---

mflowgen/Tile_MemCore/construct.py
mflowgen/common/gen_sram_macro/configure.yml
mflowgen/common/gen_sram_macro/gen_srams.sh
mflowgen/common/gen_sram_macro/mc
mflowgen/full_chip/construct.py
mflowgen/glb_tile/construct.py
mflowgen/soc/construct.py

Instead of relying on a copy of the memory compiler somewhere on the machine, I've added the memory compiler to the ADK. This PR updates our flows to use this copy of the memory compiler. 
You'll all have to pull the latest version of the ADK for this PR to work.
P.S. Sorry for the screwed up commit history. I accidentally pushed these changes to master initially.

Use mc from adk instead of stashed copy somewhere on machine

---

memory_core/memory_core_magma.py

During end-to-end test, when the last `config_addr` is the sram addr,
sram's core feature `config_en` stays high, which overrides the previous
memory content. This patch shall fix the bug. Notice that this bug
affects all the garnet chip we've built so far.

Fix memory core sram config

---

global_buffer/global_buffer_magma_helper.py
memory_core/memory_core_magma.py
requirements.txt

Fixes type error:
TypeError: Cannot wire reset (T=Out(AsyncReset)) to reset (T=In(Reset))
global_buffer/global_buffer_magma.py defines reset as `AsyncReset` so I
changed the helper to match

Make reset type consistent, use convert API for wiring up reset port

---

mflowgen/bin/setup-buildkite.sh

Default buildkite behavior uses prebuilt RTL from a docker image. So this proposed change bypasses the unnecessary 'pip install requirements.txt' initialization of the multitude of packages that would otherwise be required to build the RTL from scratch. Also added an option '--pip_install_requirements' for when/if we wanted to do the install anyway.

Bypass pip

---

mflowgen/common/fc-custom-read-design/outputs/read-design.tcl
mflowgen/common/power-domains/configure.yml
mflowgen/common/soc-rtl-v2/rtl-scripts/soc_include_paths.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_0_params.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_1_master.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_2_sys.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_3_tlx.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_4_cgra.tcl
mflowgen/full_chip/constraints/cons_scripts/clocks_5_periph.tcl
mflowgen/full_chip/constraints/cons_scripts/design_context.tcl
mflowgen/full_chip/construct.py

Converts full_chip flow to use genus for synthesis. Depends on [this mflowgen PR](https://github.com/cornell-brg/mflowgen/pull/71). Also removes designer-interface.tcl for power domains node, as overriding the designer-interface script is no longer necessary with the Genus node we are now using.

Full_chip genus

---

mflowgen/Tile_PE/construct.py
mflowgen/Tile_PE/custom-init/outputs/floorplan.tcl

This PR just adds the `core_density_target` parameter to the PE graph, similar to memtile.
Since the PE genus flow is about ~10% smaller than DC, we also need to drop the density target so that we don't see >= 90% congestion levels from the fixed buffering overhead to meet min_delay on passthrough ports.

add core density target to PE to combat smaller synth area

---

global_buffer/copy-annotate.sh
global_buffer/dump.tcl
global_buffer/rtl/global_buffer_param.svh

1. Remove unused files (`copy-annotate.sh` and `dump.tcl`)
2. Add default `global_buffer_param.svh` file.
- This header file is generated from running some python/magma code. However, just in case where python and magma is not available, I added the default header file.

Glb cleaning some files

---

mflowgen/full_chip/constraints/cons_scripts/garnet_constraints.tcl

Ensures that dragonphy floating inputs are not tied to 0 so that they can be manually connected at the end of the flow.

Add skip_pin_for_undriven_handling for dragonphy pins

---

mflowgen/global_controller/construct.py
mflowgen/global_controller/custom-init/configure.yml
mflowgen/global_controller/custom-init/outputs/floorplan.tcl

Creates target utilization parameter for glc flow and relaxes the target because I was seeing near 100% density in Innovus.

Add utilization target param to glc

---

mflowgen/common/custom-genlibdb-constraints/genlibdb-constraints.tcl

This PR brings fixes the PE/mem tile loop breaking constraints, which no longer targeted the configuration registers that controlled the pipeline registers properly after https://github.com/StanfordAHA/garnet/pull/656.
Right now, the name of the register is hard-coded to the first 20 bits (5 tracks * 4 sides=20 bits) of `config_reg_0` in each of the 2 switch boxes (16-bit and 1-bit) in the constraints. If this were to change, it would break  again, but this will work for now.

Loopbreak constraints

---

garnet.py
passes/collateral_pass/config_register.py
requirements.txt

This should dump all the config register information, including feature addr, reg addr, lo and hi. Here is some example of the output:
```json
{"name": "RMUX_T0_EAST_B1", "addr": 393217, "range": 1, "lo": 0, "hi": 1, "reg_name": "config_reg_0"}, 
{"name": "RMUX_T0_WEST_B1", "addr": 393217,  "range": 1, "lo": 3, "hi": 4, "reg_name": "config_reg_0"}, 
{"name": "RMUX_T1_NORTH_B1", "addr": 393217, "range": 1, "lo": 5, "hi": 6, "reg_name": "config_reg_0"}, 
{"name": "RMUX_T1_SOUTH_B1", "addr": 393217, "range": 1, "lo": 6, "hi": 7, "reg_name": "config_reg_0"}, 
{"name": "RMUX_T1_EAST_B1", "addr": 393217, "range": 1, "lo": 4, "hi": 5, "reg_name": "config_reg_0"}, 
{"name": "RMUX_T1_WEST_B1", "addr": 393217, "range": 1, "lo": 7, "hi": 8, "reg_name": "config_reg_0"}
```
Notice that lo and hi are …

update register pass to extract config reg map

---

mflowgen/full_chip/construct.py
mflowgen/full_chip/glb_top/configure.yml
mflowgen/full_chip/global_controller/configure.yml
mflowgen/glb_tile/rtl/gen_rtl.sh
mflowgen/glb_top/construct.py
mflowgen/glb_top/glb_tile/configure.yml
mflowgen/glb_top/rtl/gen_rtl.sh
mflowgen/global_controller/rtl/gen_rtl.sh

Since the common rtl node can now generate rtl for glb_top, glb_tile, and glc, this PR makes it such that rtl can be generated in one single location in the hierarchical graphs, rather than generating rtl separately wtihin glb_top, glb_tile, and glc subgraphs.

Glb use fullchip

---

mflowgen/common/fc-netlist-fixing/outputs/netlist-fixing.tcl

Updates fullchip netlist-fixing script to not try to delete non-existent dragonphy output nets. I realized that the constraints fix in #669 only preserved the dragonphy input nets. Since there's no actual need to preserve nets on the dragonphy outputs, I decided to fix the error in fullchip error this way instead of preserving output nets from the beginning.

Fix dragonphy outputs error in netlist-fixing

---

mflowgen/Tile_MemCore/construct.py
mflowgen/common/power-domains/outputs/pd-mem-floorplan.tcl

Quick fix for mem tile LVS. The width change associated with the diet lake merge caused a power-domains related LVS failure. A more robust fix is coming soon, but this works for now.

Reduce mem tile width and move AON left to fix LVS

---

garnet.py

Just realized that I had this written long time ago that's never been used in the actual garnet PnR. Enable this basically gives us two benefits:
1. Switching power is reduced significantly during runtime.
2. Possible combination loops are avoided during runtime.
The downside is it usually increase the routing part of bitstream by 20-30% (when the code was written). Given the condensed register feature just introduced, I expect this to be a little bit smaller.

PnR quality improvement

---

mflowgen/bin/setup-buildkite.sh

One-line fix for why the latest Friday Night Build broke. Prevents setup script from unnecessarily trying (and failing) to overwrite a perfectly good already-existing link to the mflowgen repo.

fix fnb symlink bug

---

tbg.py

Incisive (ncsim) is no longer supported by Cadence.

upgrade tbg to xcelium

---

setup.cfg

On my system I'm getting warnings related to unknown config keys:
```
/Users/lenny/miniconda3/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
/Users/lenny/miniconda3/lib/python3.8/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Un
known config ini key: codestyle_ignore
self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
/Users/lenny/miniconda3/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
/Users/lenny/miniconda3/lib/python3.8/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Un
known config ini key: codestyle_max_line_length
self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
```
it seems these entries are redundant with the `[pycodestyle]` section, and it seems that those are the …

Remove redundant (unused?) setup.cfg entries

---

mflowgen/full_chip/construct.py

This PR adds a param to the full_chip flow that controls whether or not the seal ring is included. I'm setting it to False because @ctorng mentioned that TSMC will be taking care of the sealring for the upcoming tapeout, so we don't have to add it. I'll update the drc rule deck in the ADK accordingly.

Add param to include/not include sealring in fullchip

---

requirements.txt
tests/test_interconnect/test_interconnect_cgra.py

This PR adds a test on minimal 1x1 CGRA. You can control which core to use by adjusting the `mem_ratio`. Notice that `IOSide` has to be set to `None_` to avoid creating IO tiles.
Depends on https://github.com/StanfordAHA/canal/pull/34

add 1x1 cgra test

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py

PR just simply adds the pegasus DRC node to Tile_PE and Tile_MemCore. The graphs still support the mentor calibre tool for local use.

add Pegasus DRC node to Mem and PE

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/full_chip/construct.py
mflowgen/glb_tile/construct.py
mflowgen/glb_top/construct.py
mflowgen/global_controller/construct.py
mflowgen/icovl/construct.py
mflowgen/pad_frame/construct.py
mflowgen/soc/construct.py
mflowgen/tile_array/construct.py

Adds Pegasus DRC/LVS nodes to all graphs in a way that allows everything to work on both our machines and VDE without any manual edits.
Basically if Calibre is available, it will use Calibre. Otherwise it will use Pegasus.

Pegasus steps

---

cgra/util.py
garnet.py
global_buffer/io_placement.py
io_core/io_core_magma.py
passes/clk_pass/clk_pass.py
passes/pipeline_config_pass/pipeline_config_pass.py
passes/power_domain/pd_pass.py
passes/tile_id_pass/tile_id_pass.py
requirements.txt
tests/test_io_core/test_io_core_magma.py

Most changes are already done in the upstream (i.e. canal and PnR toolchain)
1. Adjust function calls based on upstream API changes
2. Add ability to PnR virtualized apps
- Input application netlist is cut to fit inside predefined column group size (offset at origin (0, 0))
- Multiple bitstream will be generated accordingly
- `--virtualize` and `--virtualize-group-size`
3. Add ability to PnR apps in a compact fashion:
- Use updated upstream PnR API to minimize column usage
- Useful to fit multiple apps in the same fabric simultaneously
- `--compact`
Major RTL change so far is regarding the IO tiles.
1. Introduce a new IO Core that has configurable logic. PnR tools can configure the IO core to generate valid for certain cycles
- This is turned off by default when generating hardware, but …

Virtualization

---

mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_PE/constraints/common.tcl
mflowgen/common/custom-genlibdb-constraints/genlibdb-constraints.tcl

The genlibdb constraints broke on the PE again, so this PR introduces a new, more robust way of breaking the combinational loops in the tile array. Rather than assuming that the first 20 bits of config_reg_0 in the SB's control the pipeline registers, this approach preserves the RMUX_sel insts (which select the bits of the config register that control the pipeline registers, and uses `set_case_analysis` on those preserved RMUX insts to ensure that the pipeline registers are on.

Loopbreak fix

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/common/power-domains/configure.yml
mflowgen/common/power-domains/outputs/add-aon-tie-cells.tcl

Adds a separate set of commands to add tie cells to the AON domain of the pe and mem tiles when power domains are turned on. We didn't need these before because DC added the tie cells in synthesis. Genus won't do it in the same way, so we'll add them in Innovus instead.
If we don't add the tie cells to the AON domain, the hi/lo outputs of each tile are connected directly to VDD and VSS, which causes an antenna DRC violation.

Pd tie cells

---

mflowgen/full_chip/glb_top/configure.yml
mflowgen/full_chip/global_controller/configure.yml
mflowgen/full_chip/tile_array/configure.yml
mflowgen/glb_top/glb_tile/configure.yml
mflowgen/tile_array/Tile_MemCore/configure.yml
mflowgen/tile_array/Tile_PE/configure.yml

This PR adds assertions on hierarchical blocks that all sub-block outputs must exist. Prevents the annoying scenario where something fails in a hierarchical block and the block is still marked as complete by make. Also removes some old .db outputs which are no longer valid.

Hierarchical postconditions

---

mflowgen/full_chip/glb_top/get_glb_top_outputs.sh
mflowgen/full_chip/global_controller/get_global_controller_outputs.sh
mflowgen/full_chip/tile_array/get_tile_array_outputs.sh
mflowgen/glb_top/glb_tile/get_glb_outputs.sh
mflowgen/tile_array/Tile_MemCore/get_Tile_MemCore_outputs.sh
mflowgen/tile_array/Tile_PE/get_Tile_PE_outputs.sh

This PR fixes all get_\<block\>_outputs.sh scripts so that they can copy the lvs netlist from either the pegasus lvs node or the calibre lvs node, whichever one is actually run.

Update output getters to work with either pegasus or calibre lvs

---

mflowgen/full_chip/global_controller/get_global_controller_outputs.sh
mflowgen/full_chip/tile_array/get_tile_array_outputs.sh
mflowgen/tile_array/Tile_MemCore/get_Tile_MemCore_outputs.sh
mflowgen/tile_array/Tile_PE/get_Tile_PE_outputs.sh

Removes old, no longer valid gdsmerge targets from get_<block>_outputs scripts

remove unnecessary gdsmerge targets

---

mflowgen/full_chip/construct.py

Uses the new pegasus-gdsmerge-child node in https://github.com/cornell-brg/mflowgen/pull/80 to merge the dragonphy_RDL gds into the final full_chip gds.

use pegasus to merge dragonphy_rdl if calibre not available

---

garnet.py
tbg.py

`--interconnect-only` now also splits config ports among columns. As a result, fabric-level RTL will be identical as the one used in the chip.
Current limitation:
- It might be a little bit messy to implement that in `fault` since there is no `fork` semantics in `fault`. TBG still configures in serial instead of parallel.

Tbg config ports

---

mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/constraints/common.tcl
mflowgen/Tile_PE/constraints/constraints.tcl
mflowgen/Tile_PE/construct.py

Lowered density of MEM, changed constraints very slightly, and decreased clock period to 1.1ns. PT Timing signoff reports 0.008 WNS, and total area of MEM tile is 16.8K. Lowering density allows entire flow up until cadence-innovus-signoff to complete in 4h10min on arm. Keeping density at 0.74 with 1.1ns clock period is an easy to way to let postroute take a _ very _ long time.
Got rid of modes in PE genus synthesis node, which was slowing down synthesis times a lot. At 4ns, Genus went down from 30min to 6min. At 1.1ns, Genus takes 19min, and entire flow up until cadence-innovus-signoff takes 4hr49min on arm. No timing violations found, and total area (with pond) is 5907. With pond at 4ns, area was 5460.
These times were tested on arm. Let me know if I should run on VDE to make sure that …

Make Genus Faster While Increasing Clock Frequency

---

mflowgen/common/gen_sram_macro/gen_srams.sh

Tiny update to memory compiler script to make it work on both machines without having to replicate weird directory structure present on our machine.
Since we have multiple memory compilers on VDE (1 and 2 port versions of both srams and register files), I'll look into parameterizing this node to support them all in a future PR.

update gen_sram_macro to work on VDE

---

garnet.py

This allows user to provide an app name and have all the information in one place.

copy pnr files to the app folder as well

---

mflowgen/Tile_MemCore/constraints/common.tcl

After the modifications to the mem tile flow in #719 , the mem tile hung in postroute on VDE. To prevent this, I've added some of the false paths that were added to the PE here: https://github.com/StanfordAHA/garnet/blob/1912acad4469349e549e741fdf6cfd0fa72cb88a/mflowgen/Tile_PE/constraints/constraints.tcl#L43
Basically, these constraints say that paths from a configuration input to an SB data output or SB pipeline register do not need to be optimized. After adding these constraints, the mem tile no longer hangs in postroute on VDE. I suspect we may even be able to increase the utilization target again now, but I haven't tried that out, so I won't include it in this PR.

Add false paths for config->SB data outputs in mem tile

---

mflowgen/common/init-fullchip/outputs/io-fillers.tcl
mflowgen/full_chip/custom-init/outputs/place-macros.tcl

Introduces 2 changes necessary to make fullchip pass LVS in Calibre.
1. set rte nets to skip_routing. When we used dc, this would've broken the flow because dc used the net name "rte" for a wide variety of tie_hi and tie_lo nets unrelated to rte. This isn't the case with Genus, so setting this prevents Innovus from trying to route from the core area into the pad ring to connect rte nets.
2. Create M1 power net blockage around srams in full_chip. Some floorplan change between now and the last time LVS passed moved the SRAMs such that a VDD stripe aligned exactly with the RTSEL pin (which goes from M1 to M3). This VSS/RTSEL short caused LVS to fail.
You can see the full_chip run with LVS passing at /sim/ajcars/builds/fc-10-26 on r7arm-aha.

Fullchip LVS fixes

---

global_buffer/Makefile
global_buffer/systemRDL/ordt_params/glb.parms
global_controller/Makefile
global_controller/systemRDL/ordt_params/glc.parms
mflowgen/global_controller/rtl/gen_rtl.sh

This PR has two major changes
1. @thenextged and I had an issue with `systemRDL`. When it generates RTL with `async_reset`, the output RTL has a syntax that tools doesn't like. This PR manually deletes the lines that cause a problem and append the correct syntax. 
2. Fix global controller mflowgen RTL step. Set `CW_tap` path correctly.

Fix systemRDL systemverilog generation bug and global controller rtl step bug

---

global_buffer/Makefile
global_buffer/global_buffer_magma.py
global_buffer/global_buffer_magma_helper.py
global_buffer/sim/glb_test.sv
global_buffer/systemRDL/rdl_models/glb.rdl

This PR changes the bitwidth of `stride` and `range` registers in the global buffer tile.

Change stride/range configuration register

---

mflowgen/full_chip/construct.py

Just 2 small changes related to full_chip drcs.
1. Put the sealring back in  by default to avoid chip_boundary errors
2. Ensure that we use the right drc rule deck for the available drc checking tool.

Fullchip drc setup tweaks

---

mflowgen/full_chip/construct.py
mflowgen/full_chip/custom-init/outputs/place-macros.tcl

More drc tweaks and fixes for the full_chip flow:
1. Ensures that post-power drc check uses block level rule deck, not full_chip
2. tightens blockages around srams to ensure that M1 blockage does not prevent endcap placement (this was causing many drc violations).

Fullchip drc tweaks/fixes

---

mflowgen/Tile_MemCore/custom-flowgen-setup/setup.tcl
mflowgen/Tile_PE/custom-flowgen-setup/setup.tcl
mflowgen/bin/setup-buildkite.sh

I found more non-compliant tcl code in mflowgen
https://github.com/StanfordAHA/garnet/blob/master/mflowgen/Tile_PE/custom-flowgen-setup/setup.tcl
https://github.com/StanfordAHA/garnet/blob/master/mflowgen/Tile_MemCore/custom-flowgen-setup/setup.tcl
```
if {"delay_best" in $vars(delay_corners)} {
set vars(analysis_hold_${s},delay_corner)          delay_best
```
We ran into this at least once before and fixed it, for mflowgen, see https://github.com/mflowgen/mflowgen/pull/87
As before, the code works in tcl versions 8.5 and above (e.g. `/usr/bin/tclsh` on kiwi and r7arm), but not in versions 8.4 and below (e.g. `/cad/mentor/2019.1/aoi_cal_2019.1.18.11/bin/tclsh`).
This latest code has caused yet another CI hiccup for the Friday Night Builds, so I'm proposing two changes in this pull to fix …

Tclsh version

---

global_controller/README.md

Add `README.md` file to `global_controller`.
It includes JTAG OpCode table.

Add global controller README.md file

---

mflowgen/common/synopsys-ptpx-synth/configure.yml
mflowgen/common/synopsys-ptpx-synth/designer-interface.tcl

Synthesis outputs a `design.spef`, not `design.spef.gz`.

Fix spef name for post-synth power

---

tbg.py

Change tbg to handle pgm shapes over 2 dimensions. Total size is all that is needed, so just take the product of all numbers on that line.

Tbg can handle n-dim pgm image shapes

---

mflowgen/full_chip/construct.py
mflowgen/glb_top/construct.py
mflowgen/icovl/construct.py
mflowgen/pad_frame/construct.py
mflowgen/regressions/tile-pe-clock-gate/construct.py
mflowgen/soc/construct.py

I've finally updated the tsmc16 adk to be consistent with the mflowgen convention of calling the default adk view "view-standard" instead of "stdview", so this PR just changes all the flows using stdview to view-standard. For this PR to work, you'll need the latest version of the adk.

Switch all stdview adk views to view-standard

---

tests/test_app/kernel.sv
tests/test_app/map.c
tests/test_app/parser.c
tests/test_app/proc_driver.sv

This PR modifies a `glb+fabric` testbench to use `input.pgm` and `gold.pgm` instead of `.raw` files.
It also fixes buildkite fail.

Change halide input/output file extension from raw to pgm

---

.buildkite/pipeline_mflowgen.yml
.buildkite/pipelines/pmtile_synth_only.yml
.buildkite/pipelines/rtl_only.yml
mflowgen/common/rtl/gen_rtl.sh

As described in issue 786, the RTL build step can fail silently, without alerting or halting the larger chip build.
This fixes that.
Garnet build 263 (https://buildkite.com/tapeout-aha/fullchip/builds/263) shows what happens when RTL fails without this fix in place. There was no error code at the point of failure, so the RTL step completed "successfully;" the error did not manifest until later, in the "tile_array" build step, when it was too late to easily figure out what went wrong and where.
https://buildkite.com/tapeout-aha/mflowgen/builds/3986 shows what happens when the RTL step fails using this new fix. The job immediately halts with an error code, as it should.
https://buildkite.com/tapeout-aha/mflowgen/builds/3986 shows what happened after the RTL problem was fixed (it was a stale …

RTL step silent fail

---

.buildkite/bin/prh.sh

See issue https://github.com/StanfordAHA/garnet/issues/789.
Briefly, Innovus running QRC occasionally hangs with the following warning message:
```
WARNING (EXTGRMP-103) : Detected slow or hanging jobs. The following hosts are possibly having a problem:
r7arm-aha
```
This merge is designed to fix that. 
More precisely, the existing fix was finally triggered in the wild, at which point it failed to successfully kill and restart the hung jobs. I used the resulting information to refine the fix such that hopefully it will succeed next time. See file compares for details.

fixing the hang watcher

---

.buildkite/pipeline_mflowgen.yml
.buildkite/pipelines/mem_tile_only.yml
.buildkite/pipelines/pe_tile_only.yml
mflowgen/tile_array/Tile_MemCore/get_Tile_MemCore_outputs.sh
mflowgen/tile_array/Tile_PE/get_Tile_PE_outputs.sh

Also see:
* garnet issue https://github.com/StanfordAHA/garnet/issues/791
* mflowgen pull https://github.com/mflowgen/mflowgen/pull/109
The final gate-level sim step for mem tile construction has been failing for months in our weekly CI builds. However, the error status is lost during the build, so no one ever notices that anything is wrong.
This merge, plus a corresponding change in the mflowgen repo, should fix that. In the mflowgen repo, we add a `set -o pipefail` to the GLS command sequence, e.g. it used to do something like
```
mflowgen-run 2>&1 | tee mflowgen-run.log || exit 1
```
This sequence never reaches the `exit 1` command because, although the `mflowgen-run` command in the first half of the pipeline might fail, the `tee` command in the second half of the pipeline always …

GLS fails silently during mem tile build

---

tests/test_app/environment.sv
tests/test_app/kernel.sv
tests/test_app/map.c
tests/test_app/parser.h

This PR includes these two
1. Add temporary fix to memory leak issue
2. When running multiple apps, only stall corresponding columns so that It does not affect other apps.

Temporary fix to memory leak issue and stall only part of the chip during virtualization

---

.buildkite/pipeline_fullchip.yml
.buildkite/pipeline_mflowgen.yml
.buildkite/pipelines/standalone_test.yml
bin/requirements_check.sh
mflowgen/bin/cleanup-buildkite.sh
mflowgen/bin/get-step-context.sh
mflowgen/bin/setup-buildkite.sh
mflowgen/setup-garnet.sh

New mflowgen utility `get-step-context` for running a step standalone, using previously-cached predecessor steps.
Suppose you have a design with multiple mflowgen steps. A version of the design exists in some directory `/build/chip1`, but now you are putting together a new version `/build/chip2`. You want to reuse the existing chip1 collateral up through step `cadence-innovus-postroute_hold` and then rerun that step locally.
You can use this new utility `get-step-context`:
```
% cd /build/chip2
% get-step-context.sh /build/chip1 cadence-innovus-postroute_hold
% make *-cadence-innovus-postroute_hold
```
- `--help` for setup script
- check(s) to make sure `TMPDIR` exists
- tweaks to help keep `TMPDIR` clean and free of unnecessary garbage
- mflowgen install dir falls back to `/tmp` if …

get-step-context.sh for mflowgen

---

requirements.txt

Not sure why, but full_chip build no longer works without this one-line change, such that requirements.txt specifies 'egg=lake-aha' instead of 'egg=lake'.
This is a simple change but very high priority, since we cannot do weekly builds until this is approved. Thanks! - Steve

lake => lake-aha

---

mflowgen/common/rtl/gen_rtl.sh
mflowgen/full_chip/construct.py
mflowgen/full_chip/glb_top/configure.yml
mflowgen/glb_tile/construct.py
mflowgen/glb_top/construct.py
mflowgen/glb_top/glb_tile/configure.yml

This PR passes `header` folder as inputs to rtl node of sub-graphs.
`header` folder contains all `AXI` related address map information where M3 can read/wrtie.
This file will be used in SoC simulation instead of hard-fixed address of AXI registers.

Pass header files as inputs to rtl node of sub-graphs 

---

mflowgen/full_chip/constraints/cons_scripts/garnet_constraints.tcl

Oops we finalized the global-buffer pull a moment too soon. `full_chip` synthesis failed with the following error message
https://buildkite.com/tapeout-aha/fullchip/builds/306#dbb9023a-7a83-4119-a943-2303dc144f39
```
set_multicycle_path 5 -setup -through [get_pins -hier *GlobalBuffer*/*interrupt_pulse*]
Warning : Could not find requested search value. [SDC-208] [get_pins]
: The 'get_pins' command  cannot find any pins named '*GlobalBuffer*/*interrupt_pulse*'
```
This pull implements the following change
```
-set_multicycle_path 5 -setup -through [get_pins -hier *GlobalBuffer*/*interrupt_pulse*]
-set_multicycle_path 4 -hold  -through [get_pins -hier *GlobalBuffer*/*interrupt_pulse*]
+set_multicycle_path 5 -setup -through [get_pins -hier *global_buffer*/*interrupt_pulse*] …
```

fix erroneous glb signal names

---

global_buffer/Makefile
global_buffer/design/glb_bank_ctrl.py
global_buffer/design/glb_bank_memory.py
global_buffer/design/glb_bank_sram_gen.py
global_buffer/design/glb_core_load_dma.py
global_buffer/design/glb_core_pcfg_dma.py
global_buffer/design/glb_core_store_dma.py
global_buffer/design/glb_core_switch.py
global_buffer/design/global_buffer_parameter.py

This PR parameterize the `pipeline` depth in several places in `global buffer`.
By changing the parameter at the very top, we can easily control the pipeline depth.
This can be useful if we need to increase pipeline depth to meet timing during PD.

Parameterize pipeline depth to control timing

---

mflowgen/glb_top/synopsys-ptpx-gl/configure.yml
mflowgen/glb_top/synopsys-ptpx-gl/parse_report.py
mflowgen/glb_top/synopsys-ptpx-gl/ptpx.tcl
mflowgen/glb_top/synopsys-ptpx-gl/run_step.sh

This PR adds a python script to parse the power report and dump the power breakdown by blocks into `.csv` file.
There are two parameters
`instances`: (list) The top module of the breakdown.
`parse_modules`: (list) Module name of each breakdown. They follow regex.

Add script to parse power report and dump breakdown by modules

---

mflowgen/common/rtl/gen_rtl.sh
mflowgen/full_chip/construct.py

As `docker cp` does not support wildcard, this PR adds a workaround for that.

Add workaround for wildcard for docker cmd

---

requirements.txt

As per git [blog](https://github.blog/2021-09-01-improving-git-protocol-security-github/), as of today Github is no longer accepting unencrypted Git protocol, even on clones. Updated requirements.txt to comply.

Fix reqs url

---

mflowgen/test/test_module.sh

Sometimes a "make RTL" job crashes before it has had a chance to kill its docker container. This change finds and delete the stray container.
Without this change, the container remains forever as a "running" container, and its 8 GB host image cannot be deleted because docker thinks the container is using the image.

delete docker container if make job fails

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/common/rtl/configure.yml

Fixes bug from #835 that used `rtl_docker_image` param in scripts but only defined `docker_rtl_image`.

fix rtl_docker_image param name mixup

---

mflowgen/common/init-fullchip/outputs/alignment-cells.tcl
mflowgen/full_chip/custom-init/outputs/place-macros.tcl
requirements.txt

The GLB seems to have gotten bigger recently, impacting the design in ways that broke the TSMC build.
In particular, I noticed three problems
* GLB started overlapping with an alignment cell on its right side;
* lots of congestion at top left corner of GLB, where wires have to squeeze in between the top of the GLB and the bottom of the alignment-cell row above it;
* lots of congestion in and around the SRAM cells between the GLC and the GLB.
To fix the routing and overlap problems, I moved the GLB down and to the right. To allow more room for the rightward move, I took out the lower alignment cell that it was overlapping put in a position symmetrically opposite, i.e. it is now on the left side of the GLB instead of the right side.
The second thing I did was to space out the SRAMs a bit …

PD: Modified GLB placement

---

.buildkite/glb_test.yml

New command line argument for using simulatable sram - supposed to be more clear than previous `--no-sram-stub`

add sim sram to glb buildkite

---

mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_PE/constraints/common.tcl
mflowgen/Tile_PE/constraints/constraints.tcl

Sets some false paths related to configuration signals/registers in the pe and memory tiles. Innovus was unnecessarily trying to optimize these paths.

Tile false paths

---

.buildkite/pipelines/check_pe_area.sh
mflowgen/Tile_PE/construct.py

Since new capability has been added to the PE, its area has increased. This PR increases the max pe area for the CI checks.
For a better check since we're now running through floorplanning, we can directly check the widths of the PE and memory tiles, multiply the pe width by 24 and memory by 8, and ensure that's less than the chip width. Then we can perform a similar check for the height. @steveri what do you think about that? If you agree with that approach, do you have some time to look into that?
I've also removed the code that reduced the PE clock frequency for CI, since it shouldn't be necessary with the constraint updates that were introduced recently.

Mflowgen CI

---

cgra/util.py
garnet.py

This will not compile properly since all the cores don't have proper ready valid interface. As a result, this is off by default.

add ready-valid switch

---

passes/pipeline_global_pass/pipeline_global_pass.py

Noticed that the wrong wire was being removed here. Shouldn't actually affect the output rtl but it will get rid of a bunch of warnings.

fix bug that removes non-existent wire in flush pipelining pass

---

mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_PE/constraints/common.tcl
mflowgen/common/custom-genlibdb-constraints/genlibdb-constraints.tcl
mflowgen/common/synopsys-ptpx-gl/loop_break_Interconnect.tcl

TSMC CI failed in mem-tile synthesis, with the following error
https://buildkite.com/tapeout-aha/mflowgen/builds/5733
```
set rmux_cells [get_cells -hier RMUX_T*sel_inst0]
Warning : Could not find requested search value. [SDC-208] [get_cells]
: The 'get_cells' command  cannot find any cells named 'RMUX_T*sel_inst0'
set_dont_touch $rmux_cells true
Error   : A required object parameter could not be found. [TUI-61] [parse_options]
: An object of type 'subdesign|instance|net|design|libcell' named '' could not be found.
```
This is supposed to fix that. For more details, see issue https://github.com/StanfordAHA/garnet/issues/900

RMUX select instances name change

---

memory_core/memory_core_magma.py

prevent the read enable signal from spilling to the write enable on the interconnect

gate write enable on rom mode

---

mflowgen/common/power-domains/outputs/check-clamp-logic-structure.tcl

Makes power domains clamping check work whether cell drive strength is expressed with "X" or "D". Improves error reporting by showing which SB inputs aren't clamped properly and what cells they're connected to.

Make clamp check work for tsmc and gf; improve error reporting

---

mflowgen/Tile_MemCore/constraints/common.tcl
mflowgen/Tile_PE/constraints/common.tcl
mflowgen/Tile_PE/constraints/constraints.tcl

Rewrite of the constraint added in #908 
Highlights:
-adds the constraint the mem tile in addition to PE
-only applies constraint when using power domains (not needed otherwise)
-uses `set_dont_touch_network` because I found that the previous version of the constraint didn't always work.

Pd dont touch refactor

---

.buildkite/pipeline_fullchip.yml
.buildkite/pipeline_mflowgen.yml
.buildkite/pipelines/check_pe_area.sh
.buildkite/pipelines/check_tile_width.sh
.buildkite/pipelines/glb_tile.yml
.buildkite/pipelines/glb_tile_only.yml
.buildkite/pipelines/mem_tile_only.yml
.buildkite/pipelines/pe_synth_only.yml
.buildkite/pipelines/pe_tile_only.yml
.buildkite/pipelines/pmg.yml
.buildkite/pipelines/pmtile_synth_only.yml

Slowly trying to merge gf and tsmc garnet versions back into one, so we can have a single common master branch.
This first merge should be easy to approve, you can see that none of the proposed changes will affect RTL or PD build functionality in any way. (Heads up: Future merges my be more challenging.)
Before this merge, the two branches have 175 files difference between them. After this merge, that goes down to 165. It's not much, but it's a start.
```
% git diff master-dense-tsmc-amber origin/spVspV | egrep ^diff | wc -l
175
% git diff master-dense-tsmc-amber spv-merge-to-spv | egrep ^diff | wc -l
165
```
FYI the larger plan is:
- master-dense-tsmc-amber is the "official" working TSMC branch
- spVspV is the "official" working GF branch
- we hack away at the diffs until 'git diff' …

Spv merge to spv

---

memory_core/core_combiner_core.py

This tiny change lets spVspV branch *finally* pass the aha-flow test again, for the first time in many weeks I think. Many thanks to Kalhan and Jack for putting me on this trail so this could finally get done. You can see the successful aha-flow run here: https://buildkite.com/stanford-aha/aha-flow/builds/7839
After we merge this change to spVspV, I will file a pull to integrate spVspV into aha-flow master branch.
The actual bug is this: looks like commit `dbd8123`, way back on Nov 8, changed the default memory width from 64 to 16, maybe as part of "dac memory experiments?" Anyway, apparently aha-flow master was never updated to use that change, because if it had I guess we would have seen the bug? Anyway: this pull should allow us to fix that.

make spVspV work with aha-flow again

---

memory_core/core_combiner_core.py
memory_core/memory_core_magma.py
memory_core/memtile_util.py
memory_core/pond_core.py
mflowgen/full_chip/tile_array/get_tile_array_outputs.sh

This pull is 8th in a series that so far includes https://github.com/StanfordAHA/garnet/pull/934 , https://github.com/StanfordAHA/garnet/pull/935 , https://github.com/StanfordAHA/garnet/pull/937 , https://github.com/StanfordAHA/garnet/pull/938 , https://github.com/StanfordAHA/garnet/pull/939 , https://github.com/StanfordAHA/garnet/pull/941 , https://github.com/StanfordAHA/garnet/pull/943 , slowly merging gf/onyx and tsmc/amber versions back into one, for a single common master branch.
After the most recent pull https://github.com/StanfordAHA/garnet/pull/943 , the two branches had 90 files difference between them. This pull cuts that down to 84:
```
official_dense_branch=origin/master-dense-tsmc-amber
official_sparse_branch=origin/spVspV
new_sparse_branch=spv-merge-to-spv-8
git diff …
```

Spv merge to spv 8

---

mflowgen/full_chip/construct.py

The full chip graph did not work for Onyx/GF because it tried to use dragonphy without first defining it. This fixes that by ensuring that dragonphy is only in the Amber full chip graph.

Ensure that dragonphy is only in Amber fullchip graph

---

.buildkite/pipeline_checkin_gf.yml
.buildkite/pipelines/check_pe_area.sh

This should fix the `checkin-gf` CI test. We did two things: 1) turn on two buildkite agents on the GF machine `aha-gf` and 2) allow final PE tile area to be much larger without generating an error.
The full test takes about an hour, assuming two buildkite agents available on the GF machine. As of now, the full test is triggered on every branch push. The test takes about the same amount of time as a couple of the tests that alreadyour existing `aha-flow test`, so it's not really slowing anything down versus the existing test setup.
Alternatively, we could run the test only on pull requests etc., your input on this is welcome.
After this pull, we will have five tests that run (in parallel of course) on each pull:
* `build` (garnet pytests), 4 min, e.g. …

allow larger PE tile for GF CI builds

---

bin/check_docker.sh

One of my scripts does not clean up after itself, and now the buildkite client has 171 useless zero-length files `/tmp/tmp.deleteme.*`. This simple change should prevent that from happening in the future.

make script clean up after itself

---

.buildkite/pipeline_fullchip.yml
.buildkite/setup.sh
mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/common/cadence-innovus-genlib/scripts/generate-lib.tcl
mflowgen/full_chip/glb_top/get_glb_top_outputs.sh
mflowgen/full_chip/global_controller/get_global_controller_outputs.sh
mflowgen/full_chip/tile_array/get_tile_array_outputs.sh
mflowgen/glb_top/glb_tile/get_glb_outputs.sh
mflowgen/global_controller/construct.py
mflowgen/tile_array/Tile_MemCore/get_Tile_MemCore_outputs.sh
mflowgen/tile_array/Tile_PE/get_Tile_PE_outputs.sh
mflowgen/tile_array/constraints/constraints.tcl
mflowgen/tile_array/construct.py

This branch had two goals
1. Change amber to use same genlib mechanisms as onyx; in particular, now neither build uses the deprecated `genus-genlib` step.
2. Any shell script called from `mflowgen-run` should have the `pipefail` property enabled, such that a failing command in the script makes the build fail instantly.
Side effects that had to be addressed along the way:
* Added "dont-touch" properties to lo and hi nets for Tile ID because, with the new tighter lib files(?), synthesis was adding buffers(?!!), which messes up our tile-id patch-wire hack.
* Changed `generate-lib.tcl` to use a parameter for the default setup view, instead of being hard-coded.
* Added a `pin_cap_tolerance` parameter to prevent `genlib` errors, see mflowgen issue 145: …

Genlib purge

---

.buildkite/pipelines/pmg.yml
mflowgen/tile_array/construct.py

I noticed that my buildkite `mflowgen` CI tests were not working because the new subgraph code exercises a part of the tile_array step was outdated.
https://buildkite.com/tapeout-aha/mflowgen/builds/7325
```
...BUILD SUBGRAPH '19-tile_array'
FileNotFoundError: [Errno 2] No such file or directory: 
'/sim/buildkite-agent/mflowgen.master/steps/cadence-genus-genlib/configure.yml'
```
The changes in this pull do not fix the test completely, but they do fix this particular error, and should make for a cleaner code base. In particular, the amber version of `tile_array` was still using genus genlib, which no longer exists, so I changed it to use primetime genlibdb, like we do everywhere else. Note that this change should not affect onyx and opal builds at all, it just brings the amber version in …

Onyx intel16 pmg fix for new subgraph code

---

.buildkite/pipeline_checkin_gf.yml

Fixes two problems related to CI buildkite pipeline `checkin-gf`
* increases max allowable PE tile size so as to prevent tile-too-big error;
* adds soft-fail so that if and when any of the tiles fail in the future, it will not impact a pull request (because GF pass/fail should not be a gating factor on the code going forward...)
Note this *does not* fix the problem where the buildkite agent periodically cannot check out the garnet repo branch needed for the test e.g. https://buildkite.com/tapeout-aha/checkin-gf/builds/2408#018b5d3d-4a53-4925-af9d-873a5aaf41f3
```
fatal: reference is not a tree: bf30e9f33e1592036d436d94bc6100653db829d5
⚠️ Warning: Checkout failed! exit status 128 (Attempt 1/3 Retrying in 2s)
```
This error happens *before* the pipeline gets loaded, so cannot be bypassed …

checkin-gf: soft-fail + larger max area for pe tile

---

.buildkite/pipeline_checkin_gf.yml

Removing gtile from checkin-gf CI because it broke and it's annoying and I don't think anyone is going to fix it anytime soon...

turn off checkin-gf/gtile test because it is misbehaving

---

bin/rtl-goldcompare.sh
memory_core/memtile_util.py
passes/power_domain/pd_pass.py

This fixes the bug/annoyance where every `garnet.py` invocation results in the following useless preamble
```
Failed to import libraries for results parsing.  Capabilities may be limited.
Generating LALR tables
WARNING: 183 shift/reduce conflicts
```
Example BEFORE:
```
% python garnet/garnet.py --help
Failed to import libraries for results parsing.  Capabilities may be limited.
Generating LALR tables
WARNING: 183 shift/reduce conflicts
usage: garnet.py [-h] [--width WIDTH] [--height HEIGHT]
[--pipeline_config_interval PIPELINE_CONFIG_INTERVAL]
[--glb_tile_mem_size GLB_TILE_MEM_SIZE] [--input-app APP]
...
...
AFTER:
```
% python garnet/garnet.py --help
usage: garnet.py [-h] [--width WIDTH] [--height HEIGHT]
[--pipeline_config_interval PIPELINE_CONFIG_INTERVAL]
[--glb_tile_mem_size …

Eliminate annoying and USELESS garnet.py warnings / preamble

---

.buildkite/pipeline_fullchip.yml

Quick fix corrects long-standing problem where the full-chip TSMC build completes successfully, but the final "summary" step of the build throws an error because of a missing comparison file. Here are before-and-after comparisons:

prevent unnecessary fail in fullchip summary step

---

.buildkite/pipelines/pmg.yml
mflowgen/common/rtl/gen_rtl.sh

`pmg.yml` changes:
* BEFORE: each of three tests (ptile,mtile,gtile) competed to delete and reload the same docker image "garnet:latest"
* AFTER: docker image loaded *once* in a separate "setup" step before launching the three tests
`gen_rtl.sh` changes:
* BEFORE: each test would do a "docker prune" *before* launching a container, thus potentially deleting the very image that the container would use
* AFTER: "docker prune" happens *after* container launch, giving container the opportunity to reuse an existing image and preventing the prune from deleting that image (because container is using it)

Better pruning of docker images for gen_rtl.sh

---

mflowgen/Tile_MemCore/construct.py
mflowgen/Tile_PE/construct.py
mflowgen/full_chip/construct.py

Scrubbed three `mflowgen/*/construct.py` files to remove lint errors. This brings overall garnet repo lint PEP8 style error count down from 9978 to 6337:
BEFORE: https://buildkite.com/stanford-aha/garnet/builds/4981
```...........................Found 9978 E errors```
AFTER: https://buildkite.com/stanford-aha/garnet/builds/4992
```...........................Found 6337 E errors```

Remove 3000 lint errors

---

bin/rtl-goldcheck.sh
bin/rtl-goldcompare.sh

Oops, looks like the onyx gold check in the mflowgen buildkite pipeline has been silently failing for some time now. See e.g. this build, where the "Gold RTL" step says PASSED although, when you look at the log, it failed utterly because of a sed script error.
https://buildkite.com/tapeout-aha/mflowgen/builds/8124
```
Comparing 92061 lines of design.v
versus    91793 lines of onyx-4x2.v
/aha/garnet/bin/rtl-goldcompare.sh design.v onyx-4x2.v
sed: -e expression #1, char 46: unterminated `s' command
sed: -e expression #1, char 46: unterminated `s' command
Test PASSED
```
I fixed the sed script and also changed the test so that future failures will not say "PASSED".
https://buildkite.com/tapeout-aha/mflowgen/builds/8137
Note that the test still fails, but not silently, and not because of the …

Fix onyx gold bug

---

tests/test_app/lib/map.c
tests/test_app/lib/parser.c
tests/test_app/lib/parser.h
tests/test_memory_core/build_tb.py

1. Add software gold generation for sparse to dense and dense to sparse conversion.
2. Fix bug in map.c where the flush signal for tiles residing in columns larger than 16 are not configured
3. Workaround for the currently broken dense scanner. This is done by setting the "opal_dense_scanner_workaround" flag in the deisng_meta.json file. If this flag is set, the flush signal is configured to be from a unused GLB tile.

Add sparse dense conversion

---

tests/test_memory_core/build_tb.py

1. Added a opal workaround indication flag to functions to optionally enable the software workaround for the broken dense scanner in opal.
2. Added code in build_tb.py to generate GLB input file that contains the (2, 0, dim_size) input pair for the updated dense scanner.

Dense scanner fix

---

garnet.py
tests/test_app/lib/map.c
tests/test_app/lib/map.h
tests/test_app/lib/parser.c
tests/test_app/lib/parser.h
tests/test_app/tb/garnet_test.sv
tests/test_app/tb/kernel.sv

1. update testbenches to support glb tiling, which runs the same kernel multiple times for conv with large number of channels
2. add end-to-end arg in garnet.py and write 0s to interconnect config regs in bitstream to avoid random flushes caused by previous kernels

Glb tiling for dwconv

---

mflowgen/common/rtl/gen_rtl.sh

Before using the docker container, certain things must happen e.g. restoring `.git. metadata for the clockwork submodule. Normally, this happens on first invocation by way of commands in the container's `/root/.bashrc` file. Unfortunately, `.bashrc` does an early-out when the container is accessed only by `docker exec` commands, which is what garnet fullchip build currently does by default. The early-out happens before reaching the crucial command `source /aha/aha/bin/bashrc`.
This fixes that, by invoking `source /aha/aha/bin/bashrc` explicitly, without using the `.bashrc` indirection.
I'm not including anyone else on this review, because at this point I think I am the only one using fullchip builds...

aha bashrc needs to be re-examined maybe

---

mflowgen/bin/setup-buildkite.sh
mflowgen/setup-garnet.sh

Many of our CAD machines recently upgraded from Red Hat version 7 (r7) to Rocky Linux version 8 (r8). This broke some stuff. In particular, the weekly Amber full-chip builds that run on r8arm-aha (formerly r7arm-aha) needed some tweaking to make them work.
For more details see issue https://github.com/StanfordAHA/garnet/issues/1085.

CAD problems related to recent r7->r8 upgrade

---

.buildkite/bin/docker-clean.sh
.buildkite/ci.yml

These changes are designed to address the aha regression-failure problem described in aha issue 1959 https://github.com/StanfordAHA/aha/issues/1959.
I discovered two pertinent errors, both related to the garnet CI script `ci.yml`, whose "docker cleanup" step does three things
* a) delete the docker container that was used to do the CI test;
* b) look for other old/stale containers and delete them as well, by invoking a script `docker-clean.sh`;
* c) delete all unused docker images older than 24 hours.
The first error was in step (c), which is supposed to delete unused docker images. Previously, it did this with a command `docker image prune --force`. The `--force` arg was supposed to prevent the command from asking "do you really want to do this?"  Unfortunately, it had the side effect of …

Stop killing aha regressions

---

tests/test_app/tb/environment.sv

1. Fixed a bug in environment.sv where the interrupt waiting logic is ended prematurely upon the receiving the first interrupt due to the extra break statement below the mask matching check
2. Remove/Modify print statements

Fix Bug in TB

---

.buildkite/ci.yml

Currently, if two different steps in the same buildkite CI pipeline run on two different machines, it can cause trouble. I.e. if an initial step 'build docker' creates a docker image/container on r8cad-docker, and a later step 'regression 1' step tries to use that image/container, it will of course not find it.
This change ensures that the entire pipeline runs on a single machine.

restrict CI runs to a single host

---

.buildkite/ci.yml

Garnet build 5821 FAILED b/c it got an agent that cannot run docker
```
https://buildkite.com/stanford-aha/garnet/builds/5821
/bin/bash: docker: command not found
```
A similar thing happened with build 5822 <https://buildkite.com/stanford-aha/garnet/builds/5822>.
Solution: require builds to select only agents with tag `docker=true`.

Buildkite agent fix

---

zircon_wrapper/zircon.v

New pinout for zircon PD. Contains AXi ifc for MU params. MU-GLB ifc still unconnected: to be handled in a future PR.

Update zircon wrapper with MU wrapper and its new pins

---

mflowgen/common/rtl/gen_rtl.sh

gen-rtl.sh was waiting for bashrc background jobs to finish before generating RTL.
The background jobs are supposed to finish quickly, but apparently they don't always.
This change fixes the gen-rtl script so that it does not wait on the background jobs anymore, i.e. it puts the entire bashrc source job in the background.
bashrc does however do things that gen-rtl needs, but these things should only take a couple seconds at most, so I added a mandatory 60-second wait after starting the background bashrc job.

Do not wait (long) for docker bashrc

---

mflowgen/common/rtl/gen_rtl.sh

Recent changes in the lassen repo broke my weekly amber build
<https://buildkite.com/tapeout-aha/fullchip/builds/640>
This change fixes it by using an older known-good lassen version instead of the master branch
<https://buildkite.com/tapeout-aha/fullchip/builds/641>
This change affects only me and my weekly amber build, so I will spare you the need for external review...when/if the tests pass I will merge.

Freeze lassen at 77c32df from 2024

---

cgra/util_amber.py

This fixes the broken `mflowgen` buildkite pipeline.
Apparently a recent commit changed the location of an import library (`compress_config_data`).
`cgra/util_onyx.py` was updated to reflect the change, but not `util_amber.py`.
This fixes that.

Restore missing compress_config_data

---

garnet.py
matrix_unit/matrix_unit_main.py
matrix_unit/mu2cgra_pipeline_unit.py

This RTL change reduces the depth of the cgra2mu_ready_and tree from 32->1 to 16->1, which may improve timing and area. Furthermore, this path may now be optionally pipelined (to meet timing if needed) by adding "pipeline-mu2cgra" flag to the aha garnet.

Simplify cgra2mu ready and

---

zircon_wrapper/zircon.v

Pipelining of the following interconnect to close timing:
MU <-> GLB
MU <-> CGRA tile array
Because the interface is ready-valid, pipelining is done using a depth2 fifo.

Zircon timing and performance fixes

---

tests/install-verilator.sh
tests/test_app/tb/garnet_test.sv

Oops sorry guys, it looks as though the verilator-based CI has been broken for awhile. The problem appears to be 1) a new verilator-install package that stopped working 
https://github.com/StanfordAHA/garnet/actions/runs/16061689737/job/45328791009
followed by 2) a new undefined/unused external function 'get_external_mu_active_arr_env_var'
https://github.com/StanfordAHA/garnet/actions/runs/16119890790/job/45482706951
This change goes back to the older method of compiling verilator from scratch. It's slower but should be more robust. And 2) removes the unused function.

Verilator fix

---

garnet.py
matrix_unit/matrix_unit_main.py
tests/test_app/genesis_tb/top.svp
tests/test_app/lib/map.c
tests/test_app/lib/parser.c
tests/test_app/lib/parser.h
tests/test_app/tb/environment.sv
tests/test_app/tb/kernel.sv
tests/test_app/tb/proc_driver.sv

This PR includes various code fixes & improvements:
1) Modifies the gold check logic to support Zircon k-dim host tiling
2) Cleans up the E64 extent scaling logic, so that all extents in design_meta are 1:1 with the HW config
3) Fixes the fast regression, previously broken due to its incompatibility with other zircon parameters (e.g. MU port width)
Corresponding AHA PR: https://github.com/StanfordAHA/aha/pull/2065

Zircon conv5 host tiling; misc code fixes
